// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: archive.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listArchived = `-- name: ListArchived :many
SELECT 'client' AS entity, id, display_name AS label, deleted_at, deleted_by_name, delete_reason
FROM clients WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'partner', id, name, deleted_at, deleted_by_name, delete_reason
FROM partners WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'branch', id, name, deleted_at, deleted_by_name, delete_reason
FROM partner_branches WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'partner_contact', id, trim(first_name || ' ' || last_name), deleted_at, deleted_by_name, delete_reason
FROM partner_contacts WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'office', id, name, deleted_at, deleted_by_name, delete_reason
FROM offices WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'department', id, name, deleted_at, deleted_by_name, delete_reason
FROM departments WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
UNION ALL
SELECT 'tender', id, title, deleted_at, deleted_by_name, delete_reason
FROM tenders WHERE tenant_id = $1::uuid AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

type ListArchivedRow struct {
	Entity        string             `json:"entity"`
	ID            uuid.UUID          `json:"id"`
	Label         string             `json:"label"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

func (q *Queries) ListArchived(ctx context.Context, dollar_1 uuid.UUID) ([]ListArchivedRow, error) {
	rows, err := q.db.Query(ctx, listArchived, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchivedRow
	for rows.Next() {
		var i ListArchivedRow
		if err := rows.Scan(
			&i.Entity,
			&i.ID,
			&i.Label,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
