// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClients = `-- name: CountClients :one
SELECT count(*)
FROM clients c
WHERE c.tenant_id = $1 AND c.deleted_at IS NULL
  AND ($2::text = '' OR c.client_type = $2)
  AND (
    $3::text = '' OR
    c.display_name ILIKE '%' || $3 || '%' OR
    c.company_name ILIKE '%' || $3 || '%' OR
    c.email ILIKE '%' || $3 || '%' OR
    c.phone ILIKE '%' || $3 || '%'
  )
`

type CountClientsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClients, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    tenant_id, client_type, display_name, first_name, middle_name, last_name,
    id_type, id_number, company_name, reg_number, kra_pin,
    email, phone, address, notes, company_client_id, code, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, tenant_id, client_type, display_name, first_name, middle_name, last_name, id_type, id_number, company_name, reg_number, kra_pin, email, phone, address, notes, company_client_id, code, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type CreateClientParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	ClientType      string      `json:"client_type"`
	DisplayName     string      `json:"display_name"`
	FirstName       string      `json:"first_name"`
	MiddleName      string      `json:"middle_name"`
	LastName        string      `json:"last_name"`
	IDType          string      `json:"id_type"`
	IDNumber        string      `json:"id_number"`
	CompanyName     string      `json:"company_name"`
	RegNumber       string      `json:"reg_number"`
	KraPin          string      `json:"kra_pin"`
	Email           string      `json:"email"`
	Phone           string      `json:"phone"`
	Address         string      `json:"address"`
	Notes           string      `json:"notes"`
	CompanyClientID pgtype.UUID `json:"company_client_id"`
	Code            string      `json:"code"`
	CreatedByName   string      `json:"created_by_name"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.TenantID,
		arg.ClientType,
		arg.DisplayName,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.IDType,
		arg.IDNumber,
		arg.CompanyName,
		arg.RegNumber,
		arg.KraPin,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
		arg.CompanyClientID,
		arg.Code,
		arg.CreatedByName,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientType,
		&i.DisplayName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.IDType,
		&i.IDNumber,
		&i.CompanyName,
		&i.RegNumber,
		&i.KraPin,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CompanyClientID,
		&i.Code,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteClientParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const getClient = `-- name: GetClient :one
SELECT c.id, c.tenant_id, c.client_type, c.display_name, c.first_name, c.middle_name, c.last_name, c.id_type, c.id_number, c.company_name, c.reg_number, c.kra_pin, c.email, c.phone, c.address, c.notes, c.company_client_id, c.code, c.created_by_name, c.created_at, c.updated_at, c.deleted_at, c.deleted_by_name, c.delete_reason, comp.display_name AS company_client_name
FROM clients c
LEFT JOIN clients comp ON comp.id = c.company_client_id
WHERE c.id = $1 AND c.tenant_id = $2
`

type GetClientParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetClientRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ClientType        string             `json:"client_type"`
	DisplayName       string             `json:"display_name"`
	FirstName         string             `json:"first_name"`
	MiddleName        string             `json:"middle_name"`
	LastName          string             `json:"last_name"`
	IDType            string             `json:"id_type"`
	IDNumber          string             `json:"id_number"`
	CompanyName       string             `json:"company_name"`
	RegNumber         string             `json:"reg_number"`
	KraPin            string             `json:"kra_pin"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	Address           string             `json:"address"`
	Notes             string             `json:"notes"`
	CompanyClientID   pgtype.UUID        `json:"company_client_id"`
	Code              string             `json:"code"`
	CreatedByName     string             `json:"created_by_name"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName     string             `json:"deleted_by_name"`
	DeleteReason      string             `json:"delete_reason"`
	CompanyClientName *string            `json:"company_client_name"`
}

func (q *Queries) GetClient(ctx context.Context, arg GetClientParams) (GetClientRow, error) {
	row := q.db.QueryRow(ctx, getClient, arg.ID, arg.TenantID)
	var i GetClientRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientType,
		&i.DisplayName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.IDType,
		&i.IDNumber,
		&i.CompanyName,
		&i.RegNumber,
		&i.KraPin,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CompanyClientID,
		&i.Code,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
		&i.CompanyClientName,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT c.id, c.tenant_id, c.client_type, c.display_name, c.first_name, c.middle_name, c.last_name, c.id_type, c.id_number, c.company_name, c.reg_number, c.kra_pin, c.email, c.phone, c.address, c.notes, c.company_client_id, c.code, c.created_by_name, c.created_at, c.updated_at, c.deleted_at, c.deleted_by_name, c.delete_reason, comp.display_name AS company_client_name
FROM clients c
LEFT JOIN clients comp ON comp.id = c.company_client_id
WHERE c.tenant_id = $1 AND c.deleted_at IS NULL
  AND ($2::text = '' OR c.client_type = $2)
  AND (
    $3::text = '' OR
    c.display_name ILIKE '%' || $3 || '%' OR
    c.company_name ILIKE '%' || $3 || '%' OR
    c.email ILIKE '%' || $3 || '%' OR
    c.phone ILIKE '%' || $3 || '%'
  )
ORDER BY c.display_name
LIMIT $4 OFFSET $5
`

type ListClientsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListClientsRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	ClientType        string             `json:"client_type"`
	DisplayName       string             `json:"display_name"`
	FirstName         string             `json:"first_name"`
	MiddleName        string             `json:"middle_name"`
	LastName          string             `json:"last_name"`
	IDType            string             `json:"id_type"`
	IDNumber          string             `json:"id_number"`
	CompanyName       string             `json:"company_name"`
	RegNumber         string             `json:"reg_number"`
	KraPin            string             `json:"kra_pin"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	Address           string             `json:"address"`
	Notes             string             `json:"notes"`
	CompanyClientID   pgtype.UUID        `json:"company_client_id"`
	Code              string             `json:"code"`
	CreatedByName     string             `json:"created_by_name"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName     string             `json:"deleted_by_name"`
	DeleteReason      string             `json:"delete_reason"`
	CompanyClientName *string            `json:"company_client_name"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.Query(ctx, listClients,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClientsRow
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientType,
			&i.DisplayName,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.IDType,
			&i.IDNumber,
			&i.CompanyName,
			&i.RegNumber,
			&i.KraPin,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Notes,
			&i.CompanyClientID,
			&i.Code,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
			&i.CompanyClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients SET
    client_type = $3,
    display_name = $4,
    first_name = $5,
    middle_name = $6,
    last_name = $7,
    id_type = $8,
    id_number = $9,
    company_name = $10,
    reg_number = $11,
    kra_pin = $12,
    email = $13,
    phone = $14,
    address = $15,
    notes = $16,
    company_client_id = $17,
    code = $18,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_type, display_name, first_name, middle_name, last_name, id_type, id_number, company_name, reg_number, kra_pin, email, phone, address, notes, company_client_id, code, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type UpdateClientParams struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	ClientType      string      `json:"client_type"`
	DisplayName     string      `json:"display_name"`
	FirstName       string      `json:"first_name"`
	MiddleName      string      `json:"middle_name"`
	LastName        string      `json:"last_name"`
	IDType          string      `json:"id_type"`
	IDNumber        string      `json:"id_number"`
	CompanyName     string      `json:"company_name"`
	RegNumber       string      `json:"reg_number"`
	KraPin          string      `json:"kra_pin"`
	Email           string      `json:"email"`
	Phone           string      `json:"phone"`
	Address         string      `json:"address"`
	Notes           string      `json:"notes"`
	CompanyClientID pgtype.UUID `json:"company_client_id"`
	Code            string      `json:"code"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.TenantID,
		arg.ClientType,
		arg.DisplayName,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.IDType,
		arg.IDNumber,
		arg.CompanyName,
		arg.RegNumber,
		arg.KraPin,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.Notes,
		arg.CompanyClientID,
		arg.Code,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientType,
		&i.DisplayName,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.IDType,
		&i.IDNumber,
		&i.CompanyName,
		&i.RegNumber,
		&i.KraPin,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Notes,
		&i.CompanyClientID,
		&i.Code,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
