// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeFollowUp = `-- name: CompleteFollowUp :one
UPDATE customer_communications SET follow_up_required = false, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, contact_id, communication_type, direction, subject, message_body, status, communication_date, follow_up_required, follow_up_date, created_by, assigned_to, created_at, updated_at
`

type CompleteFollowUpParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CompleteFollowUp(ctx context.Context, arg CompleteFollowUpParams) (CustomerCommunication, error) {
	row := q.db.QueryRow(ctx, completeFollowUp, arg.ID, arg.TenantID)
	var i CustomerCommunication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContactID,
		&i.CommunicationType,
		&i.Direction,
		&i.Subject,
		&i.MessageBody,
		&i.Status,
		&i.CommunicationDate,
		&i.FollowUpRequired,
		&i.FollowUpDate,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCommunications = `-- name: CountCommunications :one
SELECT count(*)
FROM customer_communications c
JOIN customers cu ON cu.id = c.customer_id
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.communication_type = $2)
  AND ($3::text = '' OR c.status = $3)
  AND ($4::text = '' OR c.follow_up_required = ($4::boolean))
  AND (
    $5::text = '' OR
    cu.display_name ILIKE '%' || $5 || '%' OR
    c.subject ILIKE '%' || $5 || '%' OR
    c.message_body ILIKE '%' || $5 || '%'
  )
`

type CountCommunicationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
	Column5  string    `json:"column_5"`
}

func (q *Queries) CountCommunications(ctx context.Context, arg CountCommunicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommunications,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCommunication = `-- name: CreateCommunication :one
INSERT INTO customer_communications (
    tenant_id, customer_id, contact_id, communication_type, direction, subject,
    message_body, status, communication_date, follow_up_required, follow_up_date,
    created_by, assigned_to
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, customer_id, contact_id, communication_type, direction, subject, message_body, status, communication_date, follow_up_required, follow_up_date, created_by, assigned_to, created_at, updated_at
`

type CreateCommunicationParams struct {
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
}

func (q *Queries) CreateCommunication(ctx context.Context, arg CreateCommunicationParams) (CustomerCommunication, error) {
	row := q.db.QueryRow(ctx, createCommunication,
		arg.TenantID,
		arg.CustomerID,
		arg.ContactID,
		arg.CommunicationType,
		arg.Direction,
		arg.Subject,
		arg.MessageBody,
		arg.Status,
		arg.CommunicationDate,
		arg.FollowUpRequired,
		arg.FollowUpDate,
		arg.CreatedBy,
		arg.AssignedTo,
	)
	var i CustomerCommunication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContactID,
		&i.CommunicationType,
		&i.Direction,
		&i.Subject,
		&i.MessageBody,
		&i.Status,
		&i.CommunicationDate,
		&i.FollowUpRequired,
		&i.FollowUpDate,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCommunication = `-- name: DeleteCommunication :exec
DELETE FROM customer_communications WHERE id = $1 AND tenant_id = $2
`

type DeleteCommunicationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCommunication(ctx context.Context, arg DeleteCommunicationParams) error {
	_, err := q.db.Exec(ctx, deleteCommunication, arg.ID, arg.TenantID)
	return err
}

const getCommunicationByID = `-- name: GetCommunicationByID :one
SELECT id, tenant_id, customer_id, contact_id, communication_type, direction, subject, message_body, status, communication_date, follow_up_required, follow_up_date, created_by, assigned_to, created_at, updated_at FROM customer_communications WHERE id = $1 AND tenant_id = $2
`

type GetCommunicationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCommunicationByID(ctx context.Context, arg GetCommunicationByIDParams) (CustomerCommunication, error) {
	row := q.db.QueryRow(ctx, getCommunicationByID, arg.ID, arg.TenantID)
	var i CustomerCommunication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContactID,
		&i.CommunicationType,
		&i.Direction,
		&i.Subject,
		&i.MessageBody,
		&i.Status,
		&i.CommunicationDate,
		&i.FollowUpRequired,
		&i.FollowUpDate,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommunications = `-- name: ListCommunications :many
SELECT c.id, c.tenant_id, c.customer_id, c.contact_id, c.communication_type, c.direction, c.subject, c.message_body, c.status, c.communication_date, c.follow_up_required, c.follow_up_date, c.created_by, c.assigned_to, c.created_at, c.updated_at,
    cu.display_name AS customer_name,
    ct.first_name AS contact_first_name, ct.last_name AS contact_last_name,
    creator.name AS created_by_name,
    assignee.name AS assigned_to_name
FROM customer_communications c
JOIN customers cu ON cu.id = c.customer_id
LEFT JOIN contacts ct ON ct.id = c.contact_id
LEFT JOIN users creator ON creator.id = c.created_by
LEFT JOIN users assignee ON assignee.id = c.assigned_to
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.communication_type = $2)
  AND ($3::text = '' OR c.status = $3)
  AND ($4::text = '' OR c.follow_up_required = ($4::boolean))
  AND (
    $5::text = '' OR
    cu.display_name ILIKE '%' || $5 || '%' OR
    c.subject ILIKE '%' || $5 || '%' OR
    c.message_body ILIKE '%' || $5 || '%'
  )
ORDER BY c.communication_date DESC
LIMIT $6 OFFSET $7
`

type ListCommunicationsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
	Column5  string    `json:"column_5"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListCommunicationsRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	CustomerName      string             `json:"customer_name"`
	ContactFirstName  *string            `json:"contact_first_name"`
	ContactLastName   *string            `json:"contact_last_name"`
	CreatedByName     *string            `json:"created_by_name"`
	AssignedToName    *string            `json:"assigned_to_name"`
}

func (q *Queries) ListCommunications(ctx context.Context, arg ListCommunicationsParams) ([]ListCommunicationsRow, error) {
	rows, err := q.db.Query(ctx, listCommunications,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunicationsRow
	for rows.Next() {
		var i ListCommunicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContactID,
			&i.CommunicationType,
			&i.Direction,
			&i.Subject,
			&i.MessageBody,
			&i.Status,
			&i.CommunicationDate,
			&i.FollowUpRequired,
			&i.FollowUpDate,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.ContactFirstName,
			&i.ContactLastName,
			&i.CreatedByName,
			&i.AssignedToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunicationsByCustomer = `-- name: ListCommunicationsByCustomer :many
SELECT c.id, c.tenant_id, c.customer_id, c.contact_id, c.communication_type, c.direction, c.subject, c.message_body, c.status, c.communication_date, c.follow_up_required, c.follow_up_date, c.created_by, c.assigned_to, c.created_at, c.updated_at,
    ct.first_name AS contact_first_name, ct.last_name AS contact_last_name,
    creator.name AS created_by_name,
    assignee.name AS assigned_to_name
FROM customer_communications c
LEFT JOIN contacts ct ON ct.id = c.contact_id
LEFT JOIN users creator ON creator.id = c.created_by
LEFT JOIN users assignee ON assignee.id = c.assigned_to
WHERE c.customer_id = $1
ORDER BY c.communication_date DESC
`

type ListCommunicationsByCustomerRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	ContactFirstName  *string            `json:"contact_first_name"`
	ContactLastName   *string            `json:"contact_last_name"`
	CreatedByName     *string            `json:"created_by_name"`
	AssignedToName    *string            `json:"assigned_to_name"`
}

func (q *Queries) ListCommunicationsByCustomer(ctx context.Context, customerID uuid.UUID) ([]ListCommunicationsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listCommunicationsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommunicationsByCustomerRow
	for rows.Next() {
		var i ListCommunicationsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContactID,
			&i.CommunicationType,
			&i.Direction,
			&i.Subject,
			&i.MessageBody,
			&i.Status,
			&i.CommunicationDate,
			&i.FollowUpRequired,
			&i.FollowUpDate,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactFirstName,
			&i.ContactLastName,
			&i.CreatedByName,
			&i.AssignedToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowUpsDue = `-- name: ListFollowUpsDue :many
SELECT c.id, c.tenant_id, c.customer_id, c.contact_id, c.communication_type, c.direction, c.subject, c.message_body, c.status, c.communication_date, c.follow_up_required, c.follow_up_date, c.created_by, c.assigned_to, c.created_at, c.updated_at,
    cu.display_name AS customer_name,
    ct.first_name AS contact_first_name, ct.last_name AS contact_last_name,
    creator.name AS created_by_name,
    assignee.name AS assigned_to_name
FROM customer_communications c
JOIN customers cu ON cu.id = c.customer_id
LEFT JOIN contacts ct ON ct.id = c.contact_id
LEFT JOIN users creator ON creator.id = c.created_by
LEFT JOIN users assignee ON assignee.id = c.assigned_to
WHERE c.tenant_id = $1 AND c.follow_up_required = true
ORDER BY c.follow_up_date ASC NULLS LAST
`

type ListFollowUpsDueRow struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	CustomerName      string             `json:"customer_name"`
	ContactFirstName  *string            `json:"contact_first_name"`
	ContactLastName   *string            `json:"contact_last_name"`
	CreatedByName     *string            `json:"created_by_name"`
	AssignedToName    *string            `json:"assigned_to_name"`
}

func (q *Queries) ListFollowUpsDue(ctx context.Context, tenantID uuid.UUID) ([]ListFollowUpsDueRow, error) {
	rows, err := q.db.Query(ctx, listFollowUpsDue, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowUpsDueRow
	for rows.Next() {
		var i ListFollowUpsDueRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.ContactID,
			&i.CommunicationType,
			&i.Direction,
			&i.Subject,
			&i.MessageBody,
			&i.Status,
			&i.CommunicationDate,
			&i.FollowUpRequired,
			&i.FollowUpDate,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.ContactFirstName,
			&i.ContactLastName,
			&i.CreatedByName,
			&i.AssignedToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommunicationStatus = `-- name: UpdateCommunicationStatus :one
UPDATE customer_communications SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_id, contact_id, communication_type, direction, subject, message_body, status, communication_date, follow_up_required, follow_up_date, created_by, assigned_to, created_at, updated_at
`

type UpdateCommunicationStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateCommunicationStatus(ctx context.Context, arg UpdateCommunicationStatusParams) (CustomerCommunication, error) {
	row := q.db.QueryRow(ctx, updateCommunicationStatus, arg.ID, arg.TenantID, arg.Status)
	var i CustomerCommunication
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ContactID,
		&i.CommunicationType,
		&i.Direction,
		&i.Subject,
		&i.MessageBody,
		&i.Status,
		&i.CommunicationDate,
		&i.FollowUpRequired,
		&i.FollowUpDate,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
