// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comparables.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addComparablePhoto = `-- name: AddComparablePhoto :one
INSERT INTO comparable_photos (tenant_id, comparable_id, photo_url, caption, created_by_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, comparable_id, photo_url, caption, created_by_name, created_at
`

type AddComparablePhotoParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	ComparableID  uuid.UUID `json:"comparable_id"`
	PhotoUrl      string    `json:"photo_url"`
	Caption       string    `json:"caption"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) AddComparablePhoto(ctx context.Context, arg AddComparablePhotoParams) (ComparablePhoto, error) {
	row := q.db.QueryRow(ctx, addComparablePhoto,
		arg.TenantID,
		arg.ComparableID,
		arg.PhotoUrl,
		arg.Caption,
		arg.CreatedByName,
	)
	var i ComparablePhoto
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ComparableID,
		&i.PhotoUrl,
		&i.Caption,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const comparablePhotoCounts = `-- name: ComparablePhotoCounts :many
SELECT comparable_id, count(*) AS n
FROM comparable_photos
WHERE tenant_id = $1
GROUP BY comparable_id
`

type ComparablePhotoCountsRow struct {
	ComparableID uuid.UUID `json:"comparable_id"`
	N            int64     `json:"n"`
}

func (q *Queries) ComparablePhotoCounts(ctx context.Context, tenantID uuid.UUID) ([]ComparablePhotoCountsRow, error) {
	rows, err := q.db.Query(ctx, comparablePhotoCounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparablePhotoCountsRow
	for rows.Next() {
		var i ComparablePhotoCountsRow
		if err := rows.Scan(&i.ComparableID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countComparables = `-- name: CountComparables :one
SELECT count(*) FROM comparables
WHERE tenant_id = $1 AND deleted_at IS NULL
  AND (
    $2::text = '' OR
    parcel_ref ILIKE '%' || $2 || '%' OR
    location ILIKE '%' || $2 || '%' OR
    county ILIKE '%' || $2 || '%' OR
    source ILIKE '%' || $2 || '%' OR
    notes ILIKE '%' || $2 || '%'
  )
`

type CountComparablesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) CountComparables(ctx context.Context, arg CountComparablesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComparables, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComparable = `-- name: CreateComparable :one
INSERT INTO comparables (
    tenant_id, parcel_ref, size, location, comp_date, land_user, value, value_amount, value_date,
    source, county, notes, lat, lng, contact_phone, done_by, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, tenant_id, parcel_ref, size, location, comp_date, land_user, value, value_amount, value_date, source, county, notes, lat, lng, contact_phone, done_by, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type CreateComparableParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	ParcelRef     string    `json:"parcel_ref"`
	Size          string    `json:"size"`
	Location      string    `json:"location"`
	CompDate      string    `json:"comp_date"`
	LandUser      string    `json:"land_user"`
	Value         string    `json:"value"`
	ValueAmount   int64     `json:"value_amount"`
	ValueDate     string    `json:"value_date"`
	Source        string    `json:"source"`
	County        string    `json:"county"`
	Notes         string    `json:"notes"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	ContactPhone  string    `json:"contact_phone"`
	DoneBy        string    `json:"done_by"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateComparable(ctx context.Context, arg CreateComparableParams) (Comparable, error) {
	row := q.db.QueryRow(ctx, createComparable,
		arg.TenantID,
		arg.ParcelRef,
		arg.Size,
		arg.Location,
		arg.CompDate,
		arg.LandUser,
		arg.Value,
		arg.ValueAmount,
		arg.ValueDate,
		arg.Source,
		arg.County,
		arg.Notes,
		arg.Lat,
		arg.Lng,
		arg.ContactPhone,
		arg.DoneBy,
		arg.CreatedByName,
	)
	var i Comparable
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParcelRef,
		&i.Size,
		&i.Location,
		&i.CompDate,
		&i.LandUser,
		&i.Value,
		&i.ValueAmount,
		&i.ValueDate,
		&i.Source,
		&i.County,
		&i.Notes,
		&i.Lat,
		&i.Lng,
		&i.ContactPhone,
		&i.DoneBy,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deleteComparable = `-- name: DeleteComparable :exec
UPDATE comparables SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteComparableParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteComparable(ctx context.Context, arg DeleteComparableParams) error {
	_, err := q.db.Exec(ctx, deleteComparable,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const deleteComparablePhoto = `-- name: DeleteComparablePhoto :exec
DELETE FROM comparable_photos WHERE id = $1 AND tenant_id = $2
`

type DeleteComparablePhotoParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteComparablePhoto(ctx context.Context, arg DeleteComparablePhotoParams) error {
	_, err := q.db.Exec(ctx, deleteComparablePhoto, arg.ID, arg.TenantID)
	return err
}

const getComparable = `-- name: GetComparable :one
SELECT id, tenant_id, parcel_ref, size, location, comp_date, land_user, value, value_amount, value_date, source, county, notes, lat, lng, contact_phone, done_by, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason FROM comparables WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetComparableParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetComparable(ctx context.Context, arg GetComparableParams) (Comparable, error) {
	row := q.db.QueryRow(ctx, getComparable, arg.ID, arg.TenantID)
	var i Comparable
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParcelRef,
		&i.Size,
		&i.Location,
		&i.CompDate,
		&i.LandUser,
		&i.Value,
		&i.ValueAmount,
		&i.ValueDate,
		&i.Source,
		&i.County,
		&i.Notes,
		&i.Lat,
		&i.Lng,
		&i.ContactPhone,
		&i.DoneBy,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const listComparablePhotos = `-- name: ListComparablePhotos :many
SELECT id, tenant_id, comparable_id, photo_url, caption, created_by_name, created_at FROM comparable_photos
WHERE comparable_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
`

type ListComparablePhotosParams struct {
	ComparableID uuid.UUID `json:"comparable_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListComparablePhotos(ctx context.Context, arg ListComparablePhotosParams) ([]ComparablePhoto, error) {
	rows, err := q.db.Query(ctx, listComparablePhotos, arg.ComparableID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComparablePhoto
	for rows.Next() {
		var i ComparablePhoto
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ComparableID,
			&i.PhotoUrl,
			&i.Caption,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparables = `-- name: ListComparables :many
SELECT id, tenant_id, parcel_ref, size, location, comp_date, land_user, value, value_amount, value_date, source, county, notes, lat, lng, contact_phone, done_by, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason FROM comparables
WHERE tenant_id = $1 AND deleted_at IS NULL
  AND (
    $2::text = '' OR
    parcel_ref ILIKE '%' || $2 || '%' OR
    location ILIKE '%' || $2 || '%' OR
    county ILIKE '%' || $2 || '%' OR
    source ILIKE '%' || $2 || '%' OR
    notes ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListComparablesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListComparables(ctx context.Context, arg ListComparablesParams) ([]Comparable, error) {
	rows, err := q.db.Query(ctx, listComparables,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comparable
	for rows.Next() {
		var i Comparable
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParcelRef,
			&i.Size,
			&i.Location,
			&i.CompDate,
			&i.LandUser,
			&i.Value,
			&i.ValueAmount,
			&i.ValueDate,
			&i.Source,
			&i.County,
			&i.Notes,
			&i.Lat,
			&i.Lng,
			&i.ContactPhone,
			&i.DoneBy,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComparable = `-- name: UpdateComparable :one
UPDATE comparables SET
    parcel_ref = $3,
    size = $4,
    location = $5,
    comp_date = $6,
    land_user = $7,
    value = $8,
    value_amount = $9,
    value_date = $10,
    source = $11,
    county = $12,
    notes = $13,
    lat = $14,
    lng = $15,
    contact_phone = $16,
    done_by = $17,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, parcel_ref, size, location, comp_date, land_user, value, value_amount, value_date, source, county, notes, lat, lng, contact_phone, done_by, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type UpdateComparableParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	ParcelRef    string    `json:"parcel_ref"`
	Size         string    `json:"size"`
	Location     string    `json:"location"`
	CompDate     string    `json:"comp_date"`
	LandUser     string    `json:"land_user"`
	Value        string    `json:"value"`
	ValueAmount  int64     `json:"value_amount"`
	ValueDate    string    `json:"value_date"`
	Source       string    `json:"source"`
	County       string    `json:"county"`
	Notes        string    `json:"notes"`
	Lat          float64   `json:"lat"`
	Lng          float64   `json:"lng"`
	ContactPhone string    `json:"contact_phone"`
	DoneBy       string    `json:"done_by"`
}

func (q *Queries) UpdateComparable(ctx context.Context, arg UpdateComparableParams) (Comparable, error) {
	row := q.db.QueryRow(ctx, updateComparable,
		arg.ID,
		arg.TenantID,
		arg.ParcelRef,
		arg.Size,
		arg.Location,
		arg.CompDate,
		arg.LandUser,
		arg.Value,
		arg.ValueAmount,
		arg.ValueDate,
		arg.Source,
		arg.County,
		arg.Notes,
		arg.Lat,
		arg.Lng,
		arg.ContactPhone,
		arg.DoneBy,
	)
	var i Comparable
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParcelRef,
		&i.Size,
		&i.Location,
		&i.CompDate,
		&i.LandUser,
		&i.Value,
		&i.ValueAmount,
		&i.ValueDate,
		&i.Source,
		&i.County,
		&i.Notes,
		&i.Lat,
		&i.Lng,
		&i.ContactPhone,
		&i.DoneBy,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
