// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    tenant_id, customer_id, first_name, last_name, job_title, department,
    email, phone, alternative_phone, is_primary, communication_preference, notes, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at
`

type CreateContactParams struct {
	TenantID                uuid.UUID `json:"tenant_id"`
	CustomerID              uuid.UUID `json:"customer_id"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	JobTitle                string    `json:"job_title"`
	Department              string    `json:"department"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	AlternativePhone        string    `json:"alternative_phone"`
	IsPrimary               bool      `json:"is_primary"`
	CommunicationPreference string    `json:"communication_preference"`
	Notes                   string    `json:"notes"`
	Status                  string    `json:"status"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TenantID,
		arg.CustomerID,
		arg.FirstName,
		arg.LastName,
		arg.JobTitle,
		arg.Department,
		arg.Email,
		arg.Phone,
		arg.AlternativePhone,
		arg.IsPrimary,
		arg.CommunicationPreference,
		arg.Notes,
		arg.Status,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.Department,
		&i.Email,
		&i.Phone,
		&i.AlternativePhone,
		&i.IsPrimary,
		&i.CommunicationPreference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1 AND customer_id = $2
`

type DeleteContactParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.CustomerID)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at FROM contacts WHERE id = $1 AND customer_id = $2
`

type GetContactByIDParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, arg.ID, arg.CustomerID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.Department,
		&i.Email,
		&i.Phone,
		&i.AlternativePhone,
		&i.IsPrimary,
		&i.CommunicationPreference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactsByCustomer = `-- name: ListContactsByCustomer :many
SELECT id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at FROM contacts WHERE customer_id = $1 ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListContactsByCustomer(ctx context.Context, customerID uuid.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.FirstName,
			&i.LastName,
			&i.JobTitle,
			&i.Department,
			&i.Email,
			&i.Phone,
			&i.AlternativePhone,
			&i.IsPrimary,
			&i.CommunicationPreference,
			&i.Notes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContactPrimary = `-- name: SetContactPrimary :one
UPDATE contacts SET is_primary = true, updated_at = now()
WHERE id = $1 AND customer_id = $2
RETURNING id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at
`

type SetContactPrimaryParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
}

func (q *Queries) SetContactPrimary(ctx context.Context, arg SetContactPrimaryParams) (Contact, error) {
	row := q.db.QueryRow(ctx, setContactPrimary, arg.ID, arg.CustomerID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.Department,
		&i.Email,
		&i.Phone,
		&i.AlternativePhone,
		&i.IsPrimary,
		&i.CommunicationPreference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setContactStatus = `-- name: SetContactStatus :one
UPDATE contacts SET status = $3, updated_at = now()
WHERE id = $1 AND customer_id = $2
RETURNING id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at
`

type SetContactStatusParams struct {
	ID         uuid.UUID `json:"id"`
	CustomerID uuid.UUID `json:"customer_id"`
	Status     string    `json:"status"`
}

func (q *Queries) SetContactStatus(ctx context.Context, arg SetContactStatusParams) (Contact, error) {
	row := q.db.QueryRow(ctx, setContactStatus, arg.ID, arg.CustomerID, arg.Status)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.Department,
		&i.Email,
		&i.Phone,
		&i.AlternativePhone,
		&i.IsPrimary,
		&i.CommunicationPreference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unsetPrimaryContacts = `-- name: UnsetPrimaryContacts :exec
UPDATE contacts SET is_primary = false, updated_at = now()
WHERE customer_id = $1 AND is_primary = true
`

func (q *Queries) UnsetPrimaryContacts(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetPrimaryContacts, customerID)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
    first_name = $3,
    last_name = $4,
    job_title = $5,
    department = $6,
    email = $7,
    phone = $8,
    alternative_phone = $9,
    communication_preference = $10,
    notes = $11,
    updated_at = now()
WHERE id = $1 AND customer_id = $2
RETURNING id, tenant_id, customer_id, first_name, last_name, job_title, department, email, phone, alternative_phone, is_primary, communication_preference, notes, status, created_at, updated_at
`

type UpdateContactParams struct {
	ID                      uuid.UUID `json:"id"`
	CustomerID              uuid.UUID `json:"customer_id"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	JobTitle                string    `json:"job_title"`
	Department              string    `json:"department"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	AlternativePhone        string    `json:"alternative_phone"`
	CommunicationPreference string    `json:"communication_preference"`
	Notes                   string    `json:"notes"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.CustomerID,
		arg.FirstName,
		arg.LastName,
		arg.JobTitle,
		arg.Department,
		arg.Email,
		arg.Phone,
		arg.AlternativePhone,
		arg.CommunicationPreference,
		arg.Notes,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.Department,
		&i.Email,
		&i.Phone,
		&i.AlternativePhone,
		&i.IsPrimary,
		&i.CommunicationPreference,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
