// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToCustomer = `-- name: AddTagToCustomer :exec
INSERT INTO customer_tags (customer_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToCustomerParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToCustomer(ctx context.Context, arg AddTagToCustomerParams) error {
	_, err := q.db.Exec(ctx, addTagToCustomer, arg.CustomerID, arg.TagID)
	return err
}

const archiveCustomer = `-- name: ArchiveCustomer :one
UPDATE customers SET status = 'archived', archive_reason = $3, archived_at = now(), updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type ArchiveCustomerParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	ArchiveReason *string   `json:"archive_reason"`
}

func (q *Queries) ArchiveCustomer(ctx context.Context, arg ArchiveCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, archiveCustomer, arg.ID, arg.TenantID, arg.ArchiveReason)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignAccountOwner = `-- name: AssignAccountOwner :one
UPDATE customers SET account_owner_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type AssignAccountOwnerParams struct {
	ID             uuid.UUID   `json:"id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	AccountOwnerID pgtype.UUID `json:"account_owner_id"`
}

func (q *Queries) AssignAccountOwner(ctx context.Context, arg AssignAccountOwnerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, assignAccountOwner, arg.ID, arg.TenantID, arg.AccountOwnerID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT count(*)
FROM customers c
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = '' OR c.customer_type = $3)
  AND ($4::text = '' OR c.segment = $4)
  AND (
    $5::text = '' OR
    c.organization_name ILIKE '%' || $5 || '%' OR
    c.trading_name ILIKE '%' || $5 || '%' OR
    c.first_name ILIKE '%' || $5 || '%' OR
    c.last_name ILIKE '%' || $5 || '%' OR
    c.display_name ILIKE '%' || $5 || '%' OR
    c.primary_email ILIKE '%' || $5 || '%' OR
    c.primary_phone ILIKE '%' || $5 || '%'
  )
`

type CountCustomersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
	Column5  string    `json:"column_5"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    tenant_id, customer_type, status, segment, source, account_owner_id,
    organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size,
    first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation,
    website, description, primary_email, primary_phone, alternative_phone, address, country, state, city
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26, $27, $28, $29, $30
)
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type CreateCustomerParams struct {
	TenantID           uuid.UUID   `json:"tenant_id"`
	CustomerType       string      `json:"customer_type"`
	Status             string      `json:"status"`
	Segment            string      `json:"segment"`
	Source             string      `json:"source"`
	AccountOwnerID     pgtype.UUID `json:"account_owner_id"`
	OrganizationName   string      `json:"organization_name"`
	LegalName          string      `json:"legal_name"`
	TradingName        string      `json:"trading_name"`
	RegistrationNumber string      `json:"registration_number"`
	TaxPin             string      `json:"tax_pin"`
	Industry           string      `json:"industry"`
	OrganizationSize   string      `json:"organization_size"`
	FirstName          string      `json:"first_name"`
	MiddleName         string      `json:"middle_name"`
	LastName           string      `json:"last_name"`
	DisplayName        string      `json:"display_name"`
	IDNumber           string      `json:"id_number"`
	DateOfBirth        pgtype.Date `json:"date_of_birth"`
	Gender             string      `json:"gender"`
	Occupation         string      `json:"occupation"`
	Website            string      `json:"website"`
	Description        string      `json:"description"`
	PrimaryEmail       string      `json:"primary_email"`
	PrimaryPhone       string      `json:"primary_phone"`
	AlternativePhone   string      `json:"alternative_phone"`
	Address            string      `json:"address"`
	Country            string      `json:"country"`
	State              string      `json:"state"`
	City               string      `json:"city"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.CustomerType,
		arg.Status,
		arg.Segment,
		arg.Source,
		arg.AccountOwnerID,
		arg.OrganizationName,
		arg.LegalName,
		arg.TradingName,
		arg.RegistrationNumber,
		arg.TaxPin,
		arg.Industry,
		arg.OrganizationSize,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DisplayName,
		arg.IDNumber,
		arg.DateOfBirth,
		arg.Gender,
		arg.Occupation,
		arg.Website,
		arg.Description,
		arg.PrimaryEmail,
		arg.PrimaryPhone,
		arg.AlternativePhone,
		arg.Address,
		arg.Country,
		arg.State,
		arg.City,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerNote = `-- name: CreateCustomerNote :one
INSERT INTO customer_notes (tenant_id, customer_id, author_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, customer_id, author_id, body, created_at
`

type CreateCustomerNoteParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
}

func (q *Queries) CreateCustomerNote(ctx context.Context, arg CreateCustomerNoteParams) (CustomerNote, error) {
	row := q.db.QueryRow(ctx, createCustomerNote,
		arg.TenantID,
		arg.CustomerID,
		arg.AuthorID,
		arg.Body,
	)
	var i CustomerNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1 AND tenant_id = $2
`

type DeleteCustomerParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.TenantID)
	return err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT c.id, c.tenant_id, c.customer_type, c.status, c.segment, c.source, c.account_owner_id, c.archive_reason, c.archived_at, c.organization_name, c.legal_name, c.trading_name, c.registration_number, c.tax_pin, c.industry, c.organization_size, c.first_name, c.middle_name, c.last_name, c.display_name, c.id_number, c.date_of_birth, c.gender, c.occupation, c.website, c.description, c.primary_email, c.primary_phone, c.alternative_phone, c.address, c.country, c.state, c.city, c.created_at, c.updated_at, u.name AS account_owner_name
FROM customers c
LEFT JOIN users u ON u.id = c.account_owner_id
WHERE c.id = $1 AND c.tenant_id = $2
`

type GetCustomerByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetCustomerByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerType       string             `json:"customer_type"`
	Status             string             `json:"status"`
	Segment            string             `json:"segment"`
	Source             string             `json:"source"`
	AccountOwnerID     pgtype.UUID        `json:"account_owner_id"`
	ArchiveReason      *string            `json:"archive_reason"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OrganizationName   string             `json:"organization_name"`
	LegalName          string             `json:"legal_name"`
	TradingName        string             `json:"trading_name"`
	RegistrationNumber string             `json:"registration_number"`
	TaxPin             string             `json:"tax_pin"`
	Industry           string             `json:"industry"`
	OrganizationSize   string             `json:"organization_size"`
	FirstName          string             `json:"first_name"`
	MiddleName         string             `json:"middle_name"`
	LastName           string             `json:"last_name"`
	DisplayName        string             `json:"display_name"`
	IDNumber           string             `json:"id_number"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Gender             string             `json:"gender"`
	Occupation         string             `json:"occupation"`
	Website            string             `json:"website"`
	Description        string             `json:"description"`
	PrimaryEmail       string             `json:"primary_email"`
	PrimaryPhone       string             `json:"primary_phone"`
	AlternativePhone   string             `json:"alternative_phone"`
	Address            string             `json:"address"`
	Country            string             `json:"country"`
	State              string             `json:"state"`
	City               string             `json:"city"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	AccountOwnerName   *string            `json:"account_owner_name"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.TenantID)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountOwnerName,
	)
	return i, err
}

const listCustomerNotes = `-- name: ListCustomerNotes :many
SELECT n.id, n.tenant_id, n.customer_id, n.author_id, n.body, n.created_at, u.name AS author_name
FROM customer_notes n
LEFT JOIN users u ON u.id = n.author_id
WHERE n.customer_id = $1
ORDER BY n.created_at DESC
`

type ListCustomerNotesRow struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
	CreatedAt  time.Time   `json:"created_at"`
	AuthorName *string     `json:"author_name"`
}

func (q *Queries) ListCustomerNotes(ctx context.Context, customerID uuid.UUID) ([]ListCustomerNotesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerNotes, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerNotesRow
	for rows.Next() {
		var i ListCustomerNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerTags = `-- name: ListCustomerTags :many
SELECT t.id, t.tenant_id, t.name, t.created_at FROM tags t
JOIN customer_tags ct ON ct.tag_id = t.id
WHERE ct.customer_id = $1
ORDER BY t.name ASC
`

func (q *Queries) ListCustomerTags(ctx context.Context, customerID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listCustomerTags, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT c.id, c.tenant_id, c.customer_type, c.status, c.segment, c.source, c.account_owner_id, c.archive_reason, c.archived_at, c.organization_name, c.legal_name, c.trading_name, c.registration_number, c.tax_pin, c.industry, c.organization_size, c.first_name, c.middle_name, c.last_name, c.display_name, c.id_number, c.date_of_birth, c.gender, c.occupation, c.website, c.description, c.primary_email, c.primary_phone, c.alternative_phone, c.address, c.country, c.state, c.city, c.created_at, c.updated_at, u.name AS account_owner_name
FROM customers c
LEFT JOIN users u ON u.id = c.account_owner_id
WHERE c.tenant_id = $1
  AND ($2::text = '' OR c.status = $2)
  AND ($3::text = '' OR c.customer_type = $3)
  AND ($4::text = '' OR c.segment = $4)
  AND (
    $5::text = '' OR
    c.organization_name ILIKE '%' || $5 || '%' OR
    c.trading_name ILIKE '%' || $5 || '%' OR
    c.first_name ILIKE '%' || $5 || '%' OR
    c.last_name ILIKE '%' || $5 || '%' OR
    c.display_name ILIKE '%' || $5 || '%' OR
    c.primary_email ILIKE '%' || $5 || '%' OR
    c.primary_phone ILIKE '%' || $5 || '%'
  )
ORDER BY c.created_at DESC
LIMIT $6 OFFSET $7
`

type ListCustomersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
	Column5  string    `json:"column_5"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListCustomersRow struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerType       string             `json:"customer_type"`
	Status             string             `json:"status"`
	Segment            string             `json:"segment"`
	Source             string             `json:"source"`
	AccountOwnerID     pgtype.UUID        `json:"account_owner_id"`
	ArchiveReason      *string            `json:"archive_reason"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OrganizationName   string             `json:"organization_name"`
	LegalName          string             `json:"legal_name"`
	TradingName        string             `json:"trading_name"`
	RegistrationNumber string             `json:"registration_number"`
	TaxPin             string             `json:"tax_pin"`
	Industry           string             `json:"industry"`
	OrganizationSize   string             `json:"organization_size"`
	FirstName          string             `json:"first_name"`
	MiddleName         string             `json:"middle_name"`
	LastName           string             `json:"last_name"`
	DisplayName        string             `json:"display_name"`
	IDNumber           string             `json:"id_number"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Gender             string             `json:"gender"`
	Occupation         string             `json:"occupation"`
	Website            string             `json:"website"`
	Description        string             `json:"description"`
	PrimaryEmail       string             `json:"primary_email"`
	PrimaryPhone       string             `json:"primary_phone"`
	AlternativePhone   string             `json:"alternative_phone"`
	Address            string             `json:"address"`
	Country            string             `json:"country"`
	State              string             `json:"state"`
	City               string             `json:"city"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	AccountOwnerName   *string            `json:"account_owner_name"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CustomerType,
			&i.Status,
			&i.Segment,
			&i.Source,
			&i.AccountOwnerID,
			&i.ArchiveReason,
			&i.ArchivedAt,
			&i.OrganizationName,
			&i.LegalName,
			&i.TradingName,
			&i.RegistrationNumber,
			&i.TaxPin,
			&i.Industry,
			&i.OrganizationSize,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.DisplayName,
			&i.IDNumber,
			&i.DateOfBirth,
			&i.Gender,
			&i.Occupation,
			&i.Website,
			&i.Description,
			&i.PrimaryEmail,
			&i.PrimaryPhone,
			&i.AlternativePhone,
			&i.Address,
			&i.Country,
			&i.State,
			&i.City,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountOwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, tenant_id, name, created_at FROM tags WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context, tenantID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromCustomer = `-- name: RemoveTagFromCustomer :exec
DELETE FROM customer_tags WHERE customer_id = $1 AND tag_id = $2
`

type RemoveTagFromCustomerParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromCustomer(ctx context.Context, arg RemoveTagFromCustomerParams) error {
	_, err := q.db.Exec(ctx, removeTagFromCustomer, arg.CustomerID, arg.TagID)
	return err
}

const restoreCustomer = `-- name: RestoreCustomer :one
UPDATE customers SET status = 'active', archive_reason = NULL, archived_at = NULL, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type RestoreCustomerParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RestoreCustomer(ctx context.Context, arg RestoreCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, restoreCustomer, arg.ID, arg.TenantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCustomerStatus = `-- name: SetCustomerStatus :one
UPDATE customers SET status = $3, archive_reason = NULL, archived_at = NULL, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type SetCustomerStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) SetCustomerStatus(ctx context.Context, arg SetCustomerStatusParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerStatus, arg.ID, arg.TenantID, arg.Status)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
    segment = $3,
    source = $4,
    organization_name = $5,
    legal_name = $6,
    trading_name = $7,
    registration_number = $8,
    tax_pin = $9,
    industry = $10,
    organization_size = $11,
    first_name = $12,
    middle_name = $13,
    last_name = $14,
    display_name = $15,
    id_number = $16,
    date_of_birth = $17,
    gender = $18,
    occupation = $19,
    website = $20,
    description = $21,
    primary_email = $22,
    primary_phone = $23,
    alternative_phone = $24,
    address = $25,
    country = $26,
    state = $27,
    city = $28,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, customer_type, status, segment, source, account_owner_id, archive_reason, archived_at, organization_name, legal_name, trading_name, registration_number, tax_pin, industry, organization_size, first_name, middle_name, last_name, display_name, id_number, date_of_birth, gender, occupation, website, description, primary_email, primary_phone, alternative_phone, address, country, state, city, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID                 uuid.UUID   `json:"id"`
	TenantID           uuid.UUID   `json:"tenant_id"`
	Segment            string      `json:"segment"`
	Source             string      `json:"source"`
	OrganizationName   string      `json:"organization_name"`
	LegalName          string      `json:"legal_name"`
	TradingName        string      `json:"trading_name"`
	RegistrationNumber string      `json:"registration_number"`
	TaxPin             string      `json:"tax_pin"`
	Industry           string      `json:"industry"`
	OrganizationSize   string      `json:"organization_size"`
	FirstName          string      `json:"first_name"`
	MiddleName         string      `json:"middle_name"`
	LastName           string      `json:"last_name"`
	DisplayName        string      `json:"display_name"`
	IDNumber           string      `json:"id_number"`
	DateOfBirth        pgtype.Date `json:"date_of_birth"`
	Gender             string      `json:"gender"`
	Occupation         string      `json:"occupation"`
	Website            string      `json:"website"`
	Description        string      `json:"description"`
	PrimaryEmail       string      `json:"primary_email"`
	PrimaryPhone       string      `json:"primary_phone"`
	AlternativePhone   string      `json:"alternative_phone"`
	Address            string      `json:"address"`
	Country            string      `json:"country"`
	State              string      `json:"state"`
	City               string      `json:"city"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.TenantID,
		arg.Segment,
		arg.Source,
		arg.OrganizationName,
		arg.LegalName,
		arg.TradingName,
		arg.RegistrationNumber,
		arg.TaxPin,
		arg.Industry,
		arg.OrganizationSize,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DisplayName,
		arg.IDNumber,
		arg.DateOfBirth,
		arg.Gender,
		arg.Occupation,
		arg.Website,
		arg.Description,
		arg.PrimaryEmail,
		arg.PrimaryPhone,
		arg.AlternativePhone,
		arg.Address,
		arg.Country,
		arg.State,
		arg.City,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerType,
		&i.Status,
		&i.Segment,
		&i.Source,
		&i.AccountOwnerID,
		&i.ArchiveReason,
		&i.ArchivedAt,
		&i.OrganizationName,
		&i.LegalName,
		&i.TradingName,
		&i.RegistrationNumber,
		&i.TaxPin,
		&i.Industry,
		&i.OrganizationSize,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DisplayName,
		&i.IDNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Occupation,
		&i.Website,
		&i.Description,
		&i.PrimaryEmail,
		&i.PrimaryPhone,
		&i.AlternativePhone,
		&i.Address,
		&i.Country,
		&i.State,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (tenant_id, name) VALUES ($1, $2)
ON CONFLICT (tenant_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, tenant_id, name, created_at
`

type UpsertTagParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.TenantID, arg.Name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
