// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDepartmentMember = `-- name: AddDepartmentMember :exec
INSERT INTO department_members (tenant_id, department_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (department_id, user_id) DO NOTHING
`

type AddDepartmentMemberParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	DepartmentID uuid.UUID `json:"department_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) AddDepartmentMember(ctx context.Context, arg AddDepartmentMemberParams) error {
	_, err := q.db.Exec(ctx, addDepartmentMember, arg.TenantID, arg.DepartmentID, arg.UserID)
	return err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (tenant_id, name, description, head_user_id, created_by_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, head_user_id, created_at, updated_at, created_by_name, deleted_at, deleted_by_name, delete_reason
`

type CreateDepartmentParams struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	HeadUserID    pgtype.UUID `json:"head_user_id"`
	CreatedByName string      `json:"created_by_name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.HeadUserID,
		arg.CreatedByName,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
UPDATE departments SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteDepartmentParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT d.id, d.tenant_id, d.name, d.description, d.head_user_id, d.created_at, d.updated_at, d.created_by_name, d.deleted_at, d.deleted_by_name, d.delete_reason, u.name AS head_user_name,
    (SELECT COUNT(*) FROM department_members dm WHERE dm.department_id = d.id) AS member_count
FROM departments d
LEFT JOIN users u ON u.id = d.head_user_id
WHERE d.id = $1 AND d.tenant_id = $2
`

type GetDepartmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDepartmentRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	HeadUserID    pgtype.UUID        `json:"head_user_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
	HeadUserName  *string            `json:"head_user_name"`
	MemberCount   int64              `json:"member_count"`
}

func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (GetDepartmentRow, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.ID, arg.TenantID)
	var i GetDepartmentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
		&i.HeadUserName,
		&i.MemberCount,
	)
	return i, err
}

const listDepartmentMembers = `-- name: ListDepartmentMembers :many
SELECT u.id, u.name, u.email, dm.created_at
FROM department_members dm
JOIN users u ON u.id = dm.user_id
WHERE dm.department_id = $1
ORDER BY u.name
`

type ListDepartmentMembersRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListDepartmentMembers(ctx context.Context, departmentID uuid.UUID) ([]ListDepartmentMembersRow, error) {
	rows, err := q.db.Query(ctx, listDepartmentMembers, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepartmentMembersRow
	for rows.Next() {
		var i ListDepartmentMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT d.id, d.tenant_id, d.name, d.description, d.head_user_id, d.created_at, d.updated_at, d.created_by_name, d.deleted_at, d.deleted_by_name, d.delete_reason, u.name AS head_user_name,
    (SELECT COUNT(*) FROM department_members dm WHERE dm.department_id = d.id) AS member_count
FROM departments d
LEFT JOIN users u ON u.id = d.head_user_id
WHERE d.tenant_id = $1 AND d.deleted_at IS NULL
ORDER BY d.name
`

type ListDepartmentsRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	HeadUserID    pgtype.UUID        `json:"head_user_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
	HeadUserName  *string            `json:"head_user_name"`
	MemberCount   int64              `json:"member_count"`
}

func (q *Queries) ListDepartments(ctx context.Context, tenantID uuid.UUID) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepartmentsRow
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.HeadUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
			&i.HeadUserName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDepartment = `-- name: PurgeDepartment :exec
DELETE FROM departments WHERE id = $1 AND tenant_id = $2
`

type PurgeDepartmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) PurgeDepartment(ctx context.Context, arg PurgeDepartmentParams) error {
	_, err := q.db.Exec(ctx, purgeDepartment, arg.ID, arg.TenantID)
	return err
}

const removeDepartmentMember = `-- name: RemoveDepartmentMember :exec
DELETE FROM department_members WHERE department_id = $1 AND user_id = $2
`

type RemoveDepartmentMemberParams struct {
	DepartmentID uuid.UUID `json:"department_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveDepartmentMember(ctx context.Context, arg RemoveDepartmentMemberParams) error {
	_, err := q.db.Exec(ctx, removeDepartmentMember, arg.DepartmentID, arg.UserID)
	return err
}

const restoreDepartment = `-- name: RestoreDepartment :exec
UPDATE departments SET deleted_at = NULL, deleted_by_name = '', delete_reason = ''
WHERE id = $1 AND tenant_id = $2
`

type RestoreDepartmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RestoreDepartment(ctx context.Context, arg RestoreDepartmentParams) error {
	_, err := q.db.Exec(ctx, restoreDepartment, arg.ID, arg.TenantID)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments SET name = $3, description = $4, head_user_id = $5, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, description, head_user_id, created_at, updated_at, created_by_name, deleted_at, deleted_by_name, delete_reason
`

type UpdateDepartmentParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	HeadUserID  pgtype.UUID `json:"head_user_id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.HeadUserID,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.HeadUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
