// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCurrentVersion = `-- name: ArchiveCurrentVersion :exec
INSERT INTO document_versions (tenant_id, document_id, version_no, file_name, file_url, issue_date, expiry_date, created_by_name)
SELECT d.tenant_id, d.id, d.version_no, d.file_name, d.file_url, d.issue_date, d.expiry_date, d.created_by_name
FROM company_documents d WHERE d.id = $1 AND d.tenant_id = $2
`

type ArchiveCurrentVersionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Snapshot the document's current file + dates into the version history,
// before SetNewVersion overwrites them.
func (q *Queries) ArchiveCurrentVersion(ctx context.Context, arg ArchiveCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, archiveCurrentVersion, arg.ID, arg.TenantID)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM company_documents
WHERE tenant_id = $1
  AND ($2::text = '' OR category = $2)
  AND (
    $3::text = '' OR
    name ILIKE '%' || $3 || '%' OR
    doc_number ILIKE '%' || $3 || '%' OR
    issuer ILIKE '%' || $3 || '%' OR
    owner_name ILIKE '%' || $3 || '%'
  )
`

type CountDocumentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO company_documents (
    tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name,
    file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name, file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, version_no, active, created_by_name, created_at, updated_at
`

type CreateDocumentParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	Name            string      `json:"name"`
	Category        string      `json:"category"`
	DocNumber       string      `json:"doc_number"`
	Issuer          string      `json:"issuer"`
	Description     string      `json:"description"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	OwnerName       string      `json:"owner_name"`
	FileName        string      `json:"file_name"`
	FileUrl         string      `json:"file_url"`
	IssueDate       pgtype.Date `json:"issue_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	RenewalLeadDays int32       `json:"renewal_lead_days"`
	OnReport        bool        `json:"on_report"`
	ReportMode      string      `json:"report_mode"`
	CreatedByName   string      `json:"created_by_name"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CompanyDocument, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.DocNumber,
		arg.Issuer,
		arg.Description,
		arg.OwnerUserID,
		arg.OwnerName,
		arg.FileName,
		arg.FileUrl,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.RenewalLeadDays,
		arg.OnReport,
		arg.ReportMode,
		arg.CreatedByName,
	)
	var i CompanyDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.DocNumber,
		&i.Issuer,
		&i.Description,
		&i.OwnerUserID,
		&i.OwnerName,
		&i.FileName,
		&i.FileUrl,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.OnReport,
		&i.ReportMode,
		&i.VersionNo,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM company_documents WHERE id = $1 AND tenant_id = $2
`

type DeleteDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Hard delete, matching propsense (company_documents has no soft-delete columns).
func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.TenantID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name, file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, version_no, active, created_by_name, created_at, updated_at FROM company_documents WHERE id = $1 AND tenant_id = $2
`

type GetDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (CompanyDocument, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.TenantID)
	var i CompanyDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.DocNumber,
		&i.Issuer,
		&i.Description,
		&i.OwnerUserID,
		&i.OwnerName,
		&i.FileName,
		&i.FileUrl,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.OnReport,
		&i.ReportMode,
		&i.VersionNo,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, tenant_id, document_id, version_no, file_name, file_url, issue_date, expiry_date, created_by_name, archived_at FROM document_versions WHERE document_id = $1 AND tenant_id = $2 ORDER BY version_no DESC
`

type ListDocumentVersionsParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.VersionNo,
			&i.FileName,
			&i.FileUrl,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.CreatedByName,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many

SELECT id, tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name, file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, version_no, active, created_by_name, created_at, updated_at FROM company_documents
WHERE tenant_id = $1
  AND ($2::text = '' OR category = $2)
  AND (
    $3::text = '' OR
    name ILIKE '%' || $3 || '%' OR
    doc_number ILIKE '%' || $3 || '%' OR
    issuer ILIKE '%' || $3 || '%' OR
    owner_name ILIKE '%' || $3 || '%'
  )
ORDER BY active DESC, expiry_date NULLS LAST, name
LIMIT $4 OFFSET $5
`

type ListDocumentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

// Document Vault: company-wide/staff documents + their version history.
// ported from propsense's company_documents.sql; tenant scoping is explicit
// (every query takes tenant_id) since MojaCRM has no RLS.
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]CompanyDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyDocument
	for rows.Next() {
		var i CompanyDocument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Category,
			&i.DocNumber,
			&i.Issuer,
			&i.Description,
			&i.OwnerUserID,
			&i.OwnerName,
			&i.FileName,
			&i.FileUrl,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.RenewalLeadDays,
			&i.OnReport,
			&i.ReportMode,
			&i.VersionNo,
			&i.Active,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNewVersion = `-- name: SetNewVersion :one
UPDATE company_documents SET
    file_name = $3,
    file_url = $4,
    issue_date = $5,
    expiry_date = $6,
    version_no = version_no + 1,
    created_by_name = $7,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name, file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, version_no, active, created_by_name, created_at, updated_at
`

type SetNewVersionParams struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	FileName      string      `json:"file_name"`
	FileUrl       string      `json:"file_url"`
	IssueDate     pgtype.Date `json:"issue_date"`
	ExpiryDate    pgtype.Date `json:"expiry_date"`
	CreatedByName string      `json:"created_by_name"`
}

// Replace the current file + dates with a new version and bump the version number.
func (q *Queries) SetNewVersion(ctx context.Context, arg SetNewVersionParams) (CompanyDocument, error) {
	row := q.db.QueryRow(ctx, setNewVersion,
		arg.ID,
		arg.TenantID,
		arg.FileName,
		arg.FileUrl,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.CreatedByName,
	)
	var i CompanyDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.DocNumber,
		&i.Issuer,
		&i.Description,
		&i.OwnerUserID,
		&i.OwnerName,
		&i.FileName,
		&i.FileUrl,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.OnReport,
		&i.ReportMode,
		&i.VersionNo,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE company_documents SET
    name = $3,
    category = $4,
    doc_number = $5,
    issuer = $6,
    description = $7,
    owner_user_id = $8,
    owner_name = $9,
    issue_date = $10,
    expiry_date = $11,
    renewal_lead_days = $12,
    on_report = $13,
    report_mode = $14,
    active = $15,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, category, doc_number, issuer, description, owner_user_id, owner_name, file_name, file_url, issue_date, expiry_date, renewal_lead_days, on_report, report_mode, version_no, active, created_by_name, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Name            string      `json:"name"`
	Category        string      `json:"category"`
	DocNumber       string      `json:"doc_number"`
	Issuer          string      `json:"issuer"`
	Description     string      `json:"description"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	OwnerName       string      `json:"owner_name"`
	IssueDate       pgtype.Date `json:"issue_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	RenewalLeadDays int32       `json:"renewal_lead_days"`
	OnReport        bool        `json:"on_report"`
	ReportMode      string      `json:"report_mode"`
	Active          bool        `json:"active"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (CompanyDocument, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.DocNumber,
		arg.Issuer,
		arg.Description,
		arg.OwnerUserID,
		arg.OwnerName,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.RenewalLeadDays,
		arg.OnReport,
		arg.ReportMode,
		arg.Active,
	)
	var i CompanyDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.DocNumber,
		&i.Issuer,
		&i.Description,
		&i.OwnerUserID,
		&i.OwnerName,
		&i.FileName,
		&i.FileUrl,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.RenewalLeadDays,
		&i.OnReport,
		&i.ReportMode,
		&i.VersionNo,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
