// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inspections.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const arriveInspection = `-- name: ArriveInspection :one
UPDATE inspections SET
    status = 'arrived',
    arrived_at = now(),
    arrival_lat = $3,
    arrival_lng = $4,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at
`

type ArriveInspectionParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	ArrivalLat float64   `json:"arrival_lat"`
	ArrivalLng float64   `json:"arrival_lng"`
}

func (q *Queries) ArriveInspection(ctx context.Context, arg ArriveInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, arriveInspection,
		arg.ID,
		arg.TenantID,
		arg.ArrivalLat,
		arg.ArrivalLng,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelInspection = `-- name: CancelInspection :one
UPDATE inspections SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at
`

type CancelInspectionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CancelInspection(ctx context.Context, arg CancelInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, cancelInspection, arg.ID, arg.TenantID)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInspection = `-- name: CreateInspection :one
INSERT INTO inspections (
    tenant_id, client_id, scheduled_at, contact_name, contact_phone, notes, transport_mode, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at
`

type CreateInspectionParams struct {
	TenantID      uuid.UUID          `json:"tenant_id"`
	ClientID      uuid.UUID          `json:"client_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ContactName   string             `json:"contact_name"`
	ContactPhone  string             `json:"contact_phone"`
	Notes         string             `json:"notes"`
	TransportMode string             `json:"transport_mode"`
	CreatedByName string             `json:"created_by_name"`
}

func (q *Queries) CreateInspection(ctx context.Context, arg CreateInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, createInspection,
		arg.TenantID,
		arg.ClientID,
		arg.ScheduledAt,
		arg.ContactName,
		arg.ContactPhone,
		arg.Notes,
		arg.TransportMode,
		arg.CreatedByName,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInspectionPhoto = `-- name: CreateInspectionPhoto :one
INSERT INTO inspection_photos (
    tenant_id, client_id, inspection_id, caption, data_url, lat, lng, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, client_id, inspection_id, caption, data_url, lat, lng, taken_at, created_by_name, created_at
`

type CreateInspectionPhotoParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	ClientID      uuid.UUID `json:"client_id"`
	InspectionID  uuid.UUID `json:"inspection_id"`
	Caption       string    `json:"caption"`
	DataUrl       string    `json:"data_url"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateInspectionPhoto(ctx context.Context, arg CreateInspectionPhotoParams) (InspectionPhoto, error) {
	row := q.db.QueryRow(ctx, createInspectionPhoto,
		arg.TenantID,
		arg.ClientID,
		arg.InspectionID,
		arg.Caption,
		arg.DataUrl,
		arg.Lat,
		arg.Lng,
		arg.CreatedByName,
	)
	var i InspectionPhoto
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.InspectionID,
		&i.Caption,
		&i.DataUrl,
		&i.Lat,
		&i.Lng,
		&i.TakenAt,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInspection = `-- name: DeleteInspection :exec
DELETE FROM inspections WHERE id = $1 AND tenant_id = $2
`

type DeleteInspectionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteInspection(ctx context.Context, arg DeleteInspectionParams) error {
	_, err := q.db.Exec(ctx, deleteInspection, arg.ID, arg.TenantID)
	return err
}

const deleteInspectionPhoto = `-- name: DeleteInspectionPhoto :exec
DELETE FROM inspection_photos WHERE id = $1 AND tenant_id = $2
`

type DeleteInspectionPhotoParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteInspectionPhoto(ctx context.Context, arg DeleteInspectionPhotoParams) error {
	_, err := q.db.Exec(ctx, deleteInspectionPhoto, arg.ID, arg.TenantID)
	return err
}

const departInspection = `-- name: DepartInspection :one
UPDATE inspections SET
    status = 'completed',
    departed_at = now(),
    departure_lat = $3,
    departure_lng = $4,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at
`

type DepartInspectionParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	DepartureLat float64   `json:"departure_lat"`
	DepartureLng float64   `json:"departure_lng"`
}

func (q *Queries) DepartInspection(ctx context.Context, arg DepartInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, departInspection,
		arg.ID,
		arg.TenantID,
		arg.DepartureLat,
		arg.DepartureLng,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInspection = `-- name: GetInspection :one
SELECT id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at FROM inspections WHERE id = $1 AND tenant_id = $2
`

type GetInspectionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetInspection(ctx context.Context, arg GetInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, getInspection, arg.ID, arg.TenantID)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInspectionPhotosByInspection = `-- name: ListInspectionPhotosByInspection :many
SELECT id, tenant_id, client_id, inspection_id, caption, data_url, lat, lng, taken_at, created_by_name, created_at FROM inspection_photos
WHERE tenant_id = $1 AND inspection_id = $2
ORDER BY taken_at
`

type ListInspectionPhotosByInspectionParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	InspectionID uuid.UUID `json:"inspection_id"`
}

func (q *Queries) ListInspectionPhotosByInspection(ctx context.Context, arg ListInspectionPhotosByInspectionParams) ([]InspectionPhoto, error) {
	rows, err := q.db.Query(ctx, listInspectionPhotosByInspection, arg.TenantID, arg.InspectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InspectionPhoto
	for rows.Next() {
		var i InspectionPhoto
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.InspectionID,
			&i.Caption,
			&i.DataUrl,
			&i.Lat,
			&i.Lng,
			&i.TakenAt,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsAll = `-- name: ListInspectionsAll :many
SELECT i.id, i.tenant_id, i.client_id, i.status, i.scheduled_at, i.contact_name, i.contact_phone, i.notes, i.transport_mode, i.arrived_at, i.arrival_lat, i.arrival_lng, i.departed_at, i.departure_lat, i.departure_lng, i.created_by_name, i.created_at, i.updated_at, c.display_name AS client_name
FROM inspections i
JOIN clients c ON c.id = i.client_id
WHERE i.tenant_id = $1
ORDER BY COALESCE(i.scheduled_at, i.created_at) ASC
`

type ListInspectionsAllRow struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	ClientID      uuid.UUID          `json:"client_id"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ContactName   string             `json:"contact_name"`
	ContactPhone  string             `json:"contact_phone"`
	Notes         string             `json:"notes"`
	TransportMode string             `json:"transport_mode"`
	ArrivedAt     pgtype.Timestamptz `json:"arrived_at"`
	ArrivalLat    float64            `json:"arrival_lat"`
	ArrivalLng    float64            `json:"arrival_lng"`
	DepartedAt    pgtype.Timestamptz `json:"departed_at"`
	DepartureLat  float64            `json:"departure_lat"`
	DepartureLng  float64            `json:"departure_lng"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	ClientName    string             `json:"client_name"`
}

func (q *Queries) ListInspectionsAll(ctx context.Context, tenantID uuid.UUID) ([]ListInspectionsAllRow, error) {
	rows, err := q.db.Query(ctx, listInspectionsAll, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInspectionsAllRow
	for rows.Next() {
		var i ListInspectionsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Status,
			&i.ScheduledAt,
			&i.ContactName,
			&i.ContactPhone,
			&i.Notes,
			&i.TransportMode,
			&i.ArrivedAt,
			&i.ArrivalLat,
			&i.ArrivalLng,
			&i.DepartedAt,
			&i.DepartureLat,
			&i.DepartureLng,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInspectionsByClient = `-- name: ListInspectionsByClient :many
SELECT id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at FROM inspections
WHERE tenant_id = $1 AND client_id = $2
ORDER BY COALESCE(scheduled_at, created_at) DESC
`

type ListInspectionsByClientParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ClientID uuid.UUID `json:"client_id"`
}

func (q *Queries) ListInspectionsByClient(ctx context.Context, arg ListInspectionsByClientParams) ([]Inspection, error) {
	rows, err := q.db.Query(ctx, listInspectionsByClient, arg.TenantID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inspection
	for rows.Next() {
		var i Inspection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.Status,
			&i.ScheduledAt,
			&i.ContactName,
			&i.ContactPhone,
			&i.Notes,
			&i.TransportMode,
			&i.ArrivedAt,
			&i.ArrivalLat,
			&i.ArrivalLng,
			&i.DepartedAt,
			&i.DepartureLat,
			&i.DepartureLng,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInspection = `-- name: UpdateInspection :one
UPDATE inspections SET
    scheduled_at = $3,
    contact_name = $4,
    contact_phone = $5,
    notes = $6,
    transport_mode = $7,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, status, scheduled_at, contact_name, contact_phone, notes, transport_mode, arrived_at, arrival_lat, arrival_lng, departed_at, departure_lat, departure_lng, created_by_name, created_at, updated_at
`

type UpdateInspectionParams struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ContactName   string             `json:"contact_name"`
	ContactPhone  string             `json:"contact_phone"`
	Notes         string             `json:"notes"`
	TransportMode string             `json:"transport_mode"`
}

func (q *Queries) UpdateInspection(ctx context.Context, arg UpdateInspectionParams) (Inspection, error) {
	row := q.db.QueryRow(ctx, updateInspection,
		arg.ID,
		arg.TenantID,
		arg.ScheduledAt,
		arg.ContactName,
		arg.ContactPhone,
		arg.Notes,
		arg.TransportMode,
	)
	var i Inspection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.Status,
		&i.ScheduledAt,
		&i.ContactName,
		&i.ContactPhone,
		&i.Notes,
		&i.TransportMode,
		&i.ArrivedAt,
		&i.ArrivalLat,
		&i.ArrivalLng,
		&i.DepartedAt,
		&i.DepartureLat,
		&i.DepartureLng,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInspectionPhotoCaption = `-- name: UpdateInspectionPhotoCaption :one
UPDATE inspection_photos SET caption = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, client_id, inspection_id, caption, data_url, lat, lng, taken_at, created_by_name, created_at
`

type UpdateInspectionPhotoCaptionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Caption  string    `json:"caption"`
}

func (q *Queries) UpdateInspectionPhotoCaption(ctx context.Context, arg UpdateInspectionPhotoCaptionParams) (InspectionPhoto, error) {
	row := q.db.QueryRow(ctx, updateInspectionPhotoCaption, arg.ID, arg.TenantID, arg.Caption)
	var i InspectionPhoto
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.InspectionID,
		&i.Caption,
		&i.DataUrl,
		&i.Lat,
		&i.Lng,
		&i.TakenAt,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}
