// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Contact struct {
	ID                      uuid.UUID `json:"id"`
	TenantID                uuid.UUID `json:"tenant_id"`
	CustomerID              uuid.UUID `json:"customer_id"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	JobTitle                string    `json:"job_title"`
	Department              string    `json:"department"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	AlternativePhone        string    `json:"alternative_phone"`
	IsPrimary               bool      `json:"is_primary"`
	CommunicationPreference string    `json:"communication_preference"`
	Notes                   string    `json:"notes"`
	Status                  string    `json:"status"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

type Customer struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerType       string             `json:"customer_type"`
	Status             string             `json:"status"`
	Segment            string             `json:"segment"`
	Source             string             `json:"source"`
	AccountOwnerID     pgtype.UUID        `json:"account_owner_id"`
	ArchiveReason      *string            `json:"archive_reason"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OrganizationName   string             `json:"organization_name"`
	LegalName          string             `json:"legal_name"`
	TradingName        string             `json:"trading_name"`
	RegistrationNumber string             `json:"registration_number"`
	TaxPin             string             `json:"tax_pin"`
	Industry           string             `json:"industry"`
	OrganizationSize   string             `json:"organization_size"`
	FirstName          string             `json:"first_name"`
	MiddleName         string             `json:"middle_name"`
	LastName           string             `json:"last_name"`
	DisplayName        string             `json:"display_name"`
	IDNumber           string             `json:"id_number"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Gender             string             `json:"gender"`
	Occupation         string             `json:"occupation"`
	Website            string             `json:"website"`
	Description        string             `json:"description"`
	PrimaryEmail       string             `json:"primary_email"`
	PrimaryPhone       string             `json:"primary_phone"`
	AlternativePhone   string             `json:"alternative_phone"`
	Address            string             `json:"address"`
	Country            string             `json:"country"`
	State              string             `json:"state"`
	City               string             `json:"city"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type CustomerCommunication struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type CustomerNote struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CustomerTag struct {
	CustomerID uuid.UUID `json:"customer_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Permission struct {
	Key         string `json:"key"`
	Description string `json:"description"`
}

type PlatformAdmin struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlatformSetting struct {
	ID        bool      `json:"id"`
	AppName   string    `json:"app_name"`
	Tagline   string    `json:"tagline"`
	LogoUrl   string    `json:"logo_url"`
	IconUrl   string    `json:"icon_url"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID        uuid.UUID `json:"role_id"`
	PermissionKey string    `json:"permission_key"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	RoleID                pgtype.UUID        `json:"role_id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	PasswordHash          string             `json:"password_hash"`
	Status                string             `json:"status"`
	AvatarUrl             *string            `json:"avatar_url"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}
