// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	ClientType      string             `json:"client_type"`
	DisplayName     string             `json:"display_name"`
	FirstName       string             `json:"first_name"`
	MiddleName      string             `json:"middle_name"`
	LastName        string             `json:"last_name"`
	IDType          string             `json:"id_type"`
	IDNumber        string             `json:"id_number"`
	CompanyName     string             `json:"company_name"`
	RegNumber       string             `json:"reg_number"`
	KraPin          string             `json:"kra_pin"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Address         string             `json:"address"`
	Notes           string             `json:"notes"`
	CompanyClientID pgtype.UUID        `json:"company_client_id"`
	Code            string             `json:"code"`
	CreatedByName   string             `json:"created_by_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName   string             `json:"deleted_by_name"`
	DeleteReason    string             `json:"delete_reason"`
}

type CompanyDocument struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Name            string      `json:"name"`
	Category        string      `json:"category"`
	DocNumber       string      `json:"doc_number"`
	Issuer          string      `json:"issuer"`
	Description     string      `json:"description"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	OwnerName       string      `json:"owner_name"`
	FileName        string      `json:"file_name"`
	FileUrl         string      `json:"file_url"`
	IssueDate       pgtype.Date `json:"issue_date"`
	ExpiryDate      pgtype.Date `json:"expiry_date"`
	RenewalLeadDays int32       `json:"renewal_lead_days"`
	OnReport        bool        `json:"on_report"`
	ReportMode      string      `json:"report_mode"`
	VersionNo       int32       `json:"version_no"`
	Active          bool        `json:"active"`
	CreatedByName   string      `json:"created_by_name"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type Comparable struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	ParcelRef     string             `json:"parcel_ref"`
	Size          string             `json:"size"`
	Location      string             `json:"location"`
	CompDate      string             `json:"comp_date"`
	LandUser      string             `json:"land_user"`
	Value         string             `json:"value"`
	ValueAmount   int64              `json:"value_amount"`
	ValueDate     string             `json:"value_date"`
	Source        string             `json:"source"`
	County        string             `json:"county"`
	Notes         string             `json:"notes"`
	Lat           float64            `json:"lat"`
	Lng           float64            `json:"lng"`
	ContactPhone  string             `json:"contact_phone"`
	DoneBy        string             `json:"done_by"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

type ComparablePhoto struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	ComparableID  uuid.UUID `json:"comparable_id"`
	PhotoUrl      string    `json:"photo_url"`
	Caption       string    `json:"caption"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type Contact struct {
	ID                      uuid.UUID `json:"id"`
	TenantID                uuid.UUID `json:"tenant_id"`
	CustomerID              uuid.UUID `json:"customer_id"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	JobTitle                string    `json:"job_title"`
	Department              string    `json:"department"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	AlternativePhone        string    `json:"alternative_phone"`
	IsPrimary               bool      `json:"is_primary"`
	CommunicationPreference string    `json:"communication_preference"`
	Notes                   string    `json:"notes"`
	Status                  string    `json:"status"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

type Customer struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerType       string             `json:"customer_type"`
	Status             string             `json:"status"`
	Segment            string             `json:"segment"`
	Source             string             `json:"source"`
	AccountOwnerID     pgtype.UUID        `json:"account_owner_id"`
	ArchiveReason      *string            `json:"archive_reason"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OrganizationName   string             `json:"organization_name"`
	LegalName          string             `json:"legal_name"`
	TradingName        string             `json:"trading_name"`
	RegistrationNumber string             `json:"registration_number"`
	TaxPin             string             `json:"tax_pin"`
	Industry           string             `json:"industry"`
	OrganizationSize   string             `json:"organization_size"`
	FirstName          string             `json:"first_name"`
	MiddleName         string             `json:"middle_name"`
	LastName           string             `json:"last_name"`
	DisplayName        string             `json:"display_name"`
	IDNumber           string             `json:"id_number"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Gender             string             `json:"gender"`
	Occupation         string             `json:"occupation"`
	Website            string             `json:"website"`
	Description        string             `json:"description"`
	PrimaryEmail       string             `json:"primary_email"`
	PrimaryPhone       string             `json:"primary_phone"`
	AlternativePhone   string             `json:"alternative_phone"`
	Address            string             `json:"address"`
	Country            string             `json:"country"`
	State              string             `json:"state"`
	City               string             `json:"city"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type CustomerCommunication struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type CustomerNote struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CustomerTag struct {
	CustomerID uuid.UUID `json:"customer_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Department struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	HeadUserID    pgtype.UUID        `json:"head_user_id"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

type DepartmentMember struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	DepartmentID uuid.UUID `json:"department_id"`
	UserID       uuid.UUID `json:"user_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type DocumentVersion struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	DocumentID    uuid.UUID   `json:"document_id"`
	VersionNo     int32       `json:"version_no"`
	FileName      string      `json:"file_name"`
	FileUrl       string      `json:"file_url"`
	IssueDate     pgtype.Date `json:"issue_date"`
	ExpiryDate    pgtype.Date `json:"expiry_date"`
	CreatedByName string      `json:"created_by_name"`
	ArchivedAt    time.Time   `json:"archived_at"`
}

type Inspection struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	ClientID      uuid.UUID          `json:"client_id"`
	Status        string             `json:"status"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	ContactName   string             `json:"contact_name"`
	ContactPhone  string             `json:"contact_phone"`
	Notes         string             `json:"notes"`
	TransportMode string             `json:"transport_mode"`
	ArrivedAt     pgtype.Timestamptz `json:"arrived_at"`
	ArrivalLat    float64            `json:"arrival_lat"`
	ArrivalLng    float64            `json:"arrival_lng"`
	DepartedAt    pgtype.Timestamptz `json:"departed_at"`
	DepartureLat  float64            `json:"departure_lat"`
	DepartureLng  float64            `json:"departure_lng"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type InspectionPhoto struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	ClientID      uuid.UUID `json:"client_id"`
	InspectionID  uuid.UUID `json:"inspection_id"`
	Caption       string    `json:"caption"`
	DataUrl       string    `json:"data_url"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	TakenAt       time.Time `json:"taken_at"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type Office struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Name          string             `json:"name"`
	Code          string             `json:"code"`
	IsMain        bool               `json:"is_main"`
	Address       string             `json:"address"`
	Town          string             `json:"town"`
	Phone         string             `json:"phone"`
	Email         string             `json:"email"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedByName string             `json:"created_by_name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

type Partner struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	LogoUrl             string             `json:"logo_url"`
	Industry            string             `json:"industry"`
	PartnershipModel    string             `json:"partnership_model"`
	Status              string             `json:"status"`
	Address             string             `json:"address"`
	Town                string             `json:"town"`
	Country             string             `json:"country"`
	ContactName         string             `json:"contact_name"`
	ContactTitle        string             `json:"contact_title"`
	WorkEmail           string             `json:"work_email"`
	PhoneMobile         string             `json:"phone_mobile"`
	PhoneOffice         string             `json:"phone_office"`
	Notes               string             `json:"notes"`
	Code                string             `json:"code"`
	Type                string             `json:"type"`
	SlaDays             int32              `json:"sla_days"`
	DefaultTemplateID   pgtype.UUID        `json:"default_template_id"`
	MileageRatePerKm    int64              `json:"mileage_rate_per_km"`
	CompMinCount        int32              `json:"comp_min_count"`
	CompMaxAgeMonths    int32              `json:"comp_max_age_months"`
	CompMaxRadiusKm     int32              `json:"comp_max_radius_km"`
	CompMaxVariancePct  int32              `json:"comp_max_variance_pct"`
	CompActualSalesOnly bool               `json:"comp_actual_sales_only"`
	CreatedByName       string             `json:"created_by_name"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName       string             `json:"deleted_by_name"`
	DeleteReason        string             `json:"delete_reason"`
}

type PartnerAppendixTemplate struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Fields        []byte    `json:"fields"`
	SortOrder     int32     `json:"sort_order"`
	Active        bool      `json:"active"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type PartnerBranch struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	PartnerID     uuid.UUID          `json:"partner_id"`
	Name          string             `json:"name"`
	Town          string             `json:"town"`
	Phone         string             `json:"phone"`
	Email         string             `json:"email"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

type PartnerContact struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	PartnerID        uuid.UUID          `json:"partner_id"`
	FirstName        string             `json:"first_name"`
	MiddleName       string             `json:"middle_name"`
	LastName         string             `json:"last_name"`
	Title            string             `json:"title"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Whatsapp         string             `json:"whatsapp"`
	PreferredChannel string             `json:"preferred_channel"`
	IsActive         bool               `json:"is_active"`
	InactiveReason   string             `json:"inactive_reason"`
	CreatedByName    string             `json:"created_by_name"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName    string             `json:"deleted_by_name"`
	DeleteReason     string             `json:"delete_reason"`
}

type PartnerRequirement struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Label         string    `json:"label"`
	Detail        string    `json:"detail"`
	Kind          string    `json:"kind"`
	SortOrder     int32     `json:"sort_order"`
	Active        bool      `json:"active"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type Permission struct {
	Key         string `json:"key"`
	Description string `json:"description"`
}

type PlatformAdmin struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlatformSetting struct {
	ID        bool      `json:"id"`
	AppName   string    `json:"app_name"`
	Tagline   string    `json:"tagline"`
	LogoUrl   string    `json:"logo_url"`
	IconUrl   string    `json:"icon_url"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ReferenceDatum struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Category      string             `json:"category"`
	Value         string             `json:"value"`
	Label         string             `json:"label"`
	SortOrder     int32              `json:"sort_order"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID        uuid.UUID `json:"role_id"`
	PermissionKey string    `json:"permission_key"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Tenant struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Status         string    `json:"status"`
	Plan           string    `json:"plan"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Country        string    `json:"country"`
	LegalName      string    `json:"legal_name"`
	RegistrationNo string    `json:"registration_no"`
	KraPin         string    `json:"kra_pin"`
	Phone          string    `json:"phone"`
	Email          string    `json:"email"`
	Website        string    `json:"website"`
	MailSenderName string    `json:"mail_sender_name"`
	MailReplyTo    string    `json:"mail_reply_to"`
	InvoiceCc      string    `json:"invoice_cc"`
	InvoiceBcc     string    `json:"invoice_bcc"`
	BillingEmail   string    `json:"billing_email"`
}

type Tender struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	Title              string             `json:"title"`
	Reference          string             `json:"reference"`
	Issuer             string             `json:"issuer"`
	Type               string             `json:"type"`
	Category           string             `json:"category"`
	Description        string             `json:"description"`
	Stage              string             `json:"stage"`
	OutcomeNote        string             `json:"outcome_note"`
	SubmissionDeadline string             `json:"submission_deadline"`
	OpeningDatetime    string             `json:"opening_datetime"`
	SubmittedOn        string             `json:"submitted_on"`
	SubmissionMethod   string             `json:"submission_method"`
	SubmissionAddress  string             `json:"submission_address"`
	SubmissionEmail    string             `json:"submission_email"`
	SubmissionContact  string             `json:"submission_contact"`
	EstimatedValue     int64              `json:"estimated_value"`
	DocFee             int64              `json:"doc_fee"`
	Currency           string             `json:"currency"`
	SecurityType       string             `json:"security_type"`
	SecurityAmount     int64              `json:"security_amount"`
	SecurityValidity   string             `json:"security_validity"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Signed             bool               `json:"signed"`
	Requirements       []byte             `json:"requirements"`
	StageLog           []byte             `json:"stage_log"`
	SubmissionLog      []byte             `json:"submission_log"`
	ContactName        string             `json:"contact_name"`
	ContactEmail       string             `json:"contact_email"`
	Notes              string             `json:"notes"`
	Reminded7dAt       pgtype.Timestamptz `json:"reminded_7d_at"`
	Reminded1dAt       pgtype.Timestamptz `json:"reminded_1d_at"`
	CreatedByName      string             `json:"created_by_name"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName      string             `json:"deleted_by_name"`
	DeleteReason       string             `json:"delete_reason"`
}

type TenderDocument struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	TenderID      uuid.UUID `json:"tender_id"`
	Name          string    `json:"name"`
	Label         string    `json:"label"`
	Kind          string    `json:"kind"`
	DataUrl       string    `json:"data_url"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type TenderLetter struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Name            string             `json:"name"`
	Kind            string             `json:"kind"`
	TemplateContent string             `json:"template_content"`
	IsDefault       bool               `json:"is_default"`
	CreatedByName   string             `json:"created_by_name"`
	CreatedAt       time.Time          `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	RoleID                pgtype.UUID        `json:"role_id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	PasswordHash          string             `json:"password_hash"`
	Status                string             `json:"status"`
	AvatarUrl             *string            `json:"avatar_url"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}
