// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	ClientType      string             `json:"client_type"`
	DisplayName     string             `json:"display_name"`
	FirstName       string             `json:"first_name"`
	MiddleName      string             `json:"middle_name"`
	LastName        string             `json:"last_name"`
	IDType          string             `json:"id_type"`
	IDNumber        string             `json:"id_number"`
	CompanyName     string             `json:"company_name"`
	RegNumber       string             `json:"reg_number"`
	KraPin          string             `json:"kra_pin"`
	Email           string             `json:"email"`
	Phone           string             `json:"phone"`
	Address         string             `json:"address"`
	Notes           string             `json:"notes"`
	CompanyClientID pgtype.UUID        `json:"company_client_id"`
	Code            string             `json:"code"`
	CreatedByName   string             `json:"created_by_name"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName   string             `json:"deleted_by_name"`
	DeleteReason    string             `json:"delete_reason"`
}

type Contact struct {
	ID                      uuid.UUID `json:"id"`
	TenantID                uuid.UUID `json:"tenant_id"`
	CustomerID              uuid.UUID `json:"customer_id"`
	FirstName               string    `json:"first_name"`
	LastName                string    `json:"last_name"`
	JobTitle                string    `json:"job_title"`
	Department              string    `json:"department"`
	Email                   string    `json:"email"`
	Phone                   string    `json:"phone"`
	AlternativePhone        string    `json:"alternative_phone"`
	IsPrimary               bool      `json:"is_primary"`
	CommunicationPreference string    `json:"communication_preference"`
	Notes                   string    `json:"notes"`
	Status                  string    `json:"status"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

type Customer struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	CustomerType       string             `json:"customer_type"`
	Status             string             `json:"status"`
	Segment            string             `json:"segment"`
	Source             string             `json:"source"`
	AccountOwnerID     pgtype.UUID        `json:"account_owner_id"`
	ArchiveReason      *string            `json:"archive_reason"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	OrganizationName   string             `json:"organization_name"`
	LegalName          string             `json:"legal_name"`
	TradingName        string             `json:"trading_name"`
	RegistrationNumber string             `json:"registration_number"`
	TaxPin             string             `json:"tax_pin"`
	Industry           string             `json:"industry"`
	OrganizationSize   string             `json:"organization_size"`
	FirstName          string             `json:"first_name"`
	MiddleName         string             `json:"middle_name"`
	LastName           string             `json:"last_name"`
	DisplayName        string             `json:"display_name"`
	IDNumber           string             `json:"id_number"`
	DateOfBirth        pgtype.Date        `json:"date_of_birth"`
	Gender             string             `json:"gender"`
	Occupation         string             `json:"occupation"`
	Website            string             `json:"website"`
	Description        string             `json:"description"`
	PrimaryEmail       string             `json:"primary_email"`
	PrimaryPhone       string             `json:"primary_phone"`
	AlternativePhone   string             `json:"alternative_phone"`
	Address            string             `json:"address"`
	Country            string             `json:"country"`
	State              string             `json:"state"`
	City               string             `json:"city"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type CustomerCommunication struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CustomerID        uuid.UUID          `json:"customer_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CommunicationType string             `json:"communication_type"`
	Direction         string             `json:"direction"`
	Subject           string             `json:"subject"`
	MessageBody       string             `json:"message_body"`
	Status            string             `json:"status"`
	CommunicationDate time.Time          `json:"communication_date"`
	FollowUpRequired  bool               `json:"follow_up_required"`
	FollowUpDate      pgtype.Timestamptz `json:"follow_up_date"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	AssignedTo        pgtype.UUID        `json:"assigned_to"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type CustomerNote struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	CustomerID uuid.UUID   `json:"customer_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Body       string      `json:"body"`
	CreatedAt  time.Time   `json:"created_at"`
}

type CustomerTag struct {
	CustomerID uuid.UUID `json:"customer_id"`
	TagID      uuid.UUID `json:"tag_id"`
}

type Partner struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Name                string             `json:"name"`
	LogoUrl             string             `json:"logo_url"`
	Industry            string             `json:"industry"`
	PartnershipModel    string             `json:"partnership_model"`
	Status              string             `json:"status"`
	Address             string             `json:"address"`
	Town                string             `json:"town"`
	Country             string             `json:"country"`
	ContactName         string             `json:"contact_name"`
	ContactTitle        string             `json:"contact_title"`
	WorkEmail           string             `json:"work_email"`
	PhoneMobile         string             `json:"phone_mobile"`
	PhoneOffice         string             `json:"phone_office"`
	Notes               string             `json:"notes"`
	Code                string             `json:"code"`
	Type                string             `json:"type"`
	SlaDays             int32              `json:"sla_days"`
	DefaultTemplateID   pgtype.UUID        `json:"default_template_id"`
	MileageRatePerKm    int64              `json:"mileage_rate_per_km"`
	CompMinCount        int32              `json:"comp_min_count"`
	CompMaxAgeMonths    int32              `json:"comp_max_age_months"`
	CompMaxRadiusKm     int32              `json:"comp_max_radius_km"`
	CompMaxVariancePct  int32              `json:"comp_max_variance_pct"`
	CompActualSalesOnly bool               `json:"comp_actual_sales_only"`
	CreatedByName       string             `json:"created_by_name"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName       string             `json:"deleted_by_name"`
	DeleteReason        string             `json:"delete_reason"`
}

type PartnerAppendixTemplate struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Fields        []byte    `json:"fields"`
	SortOrder     int32     `json:"sort_order"`
	Active        bool      `json:"active"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type PartnerBranch struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	PartnerID     uuid.UUID          `json:"partner_id"`
	Name          string             `json:"name"`
	Town          string             `json:"town"`
	Phone         string             `json:"phone"`
	Email         string             `json:"email"`
	CreatedByName string             `json:"created_by_name"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	DeleteReason  string             `json:"delete_reason"`
}

type PartnerContact struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	PartnerID        uuid.UUID          `json:"partner_id"`
	FirstName        string             `json:"first_name"`
	MiddleName       string             `json:"middle_name"`
	LastName         string             `json:"last_name"`
	Title            string             `json:"title"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Whatsapp         string             `json:"whatsapp"`
	PreferredChannel string             `json:"preferred_channel"`
	IsActive         bool               `json:"is_active"`
	InactiveReason   string             `json:"inactive_reason"`
	CreatedByName    string             `json:"created_by_name"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName    string             `json:"deleted_by_name"`
	DeleteReason     string             `json:"delete_reason"`
}

type PartnerRequirement struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Label         string    `json:"label"`
	Detail        string    `json:"detail"`
	Kind          string    `json:"kind"`
	SortOrder     int32     `json:"sort_order"`
	Active        bool      `json:"active"`
	CreatedByName string    `json:"created_by_name"`
	CreatedAt     time.Time `json:"created_at"`
}

type Permission struct {
	Key         string `json:"key"`
	Description string `json:"description"`
}

type PlatformAdmin struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlatformSetting struct {
	ID        bool      `json:"id"`
	AppName   string    `json:"app_name"`
	Tagline   string    `json:"tagline"`
	LogoUrl   string    `json:"logo_url"`
	IconUrl   string    `json:"icon_url"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID        uuid.UUID `json:"role_id"`
	PermissionKey string    `json:"permission_key"`
}

type Tag struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Status    string    `json:"status"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	RoleID                pgtype.UUID        `json:"role_id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	PasswordHash          string             `json:"password_hash"`
	Status                string             `json:"status"`
	AvatarUrl             *string            `json:"avatar_url"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}
