// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: offices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOffice = `-- name: CreateOffice :one
INSERT INTO offices (tenant_id, name, code, is_main, address, town, phone, email, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, name, code, is_main, address, town, phone, email, created_at, updated_at, created_by_name, deleted_at, deleted_by_name, delete_reason
`

type CreateOfficeParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	Name          string    `json:"name"`
	Code          string    `json:"code"`
	IsMain        bool      `json:"is_main"`
	Address       string    `json:"address"`
	Town          string    `json:"town"`
	Phone         string    `json:"phone"`
	Email         string    `json:"email"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateOffice(ctx context.Context, arg CreateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, createOffice,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.IsMain,
		arg.Address,
		arg.Town,
		arg.Phone,
		arg.Email,
		arg.CreatedByName,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.IsMain,
		&i.Address,
		&i.Town,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deleteOffice = `-- name: DeleteOffice :exec
UPDATE offices SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteOfficeParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteOffice(ctx context.Context, arg DeleteOfficeParams) error {
	_, err := q.db.Exec(ctx, deleteOffice,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const listOffices = `-- name: ListOffices :many
SELECT id, tenant_id, name, code, is_main, address, town, phone, email, created_at, updated_at, created_by_name, deleted_at, deleted_by_name, delete_reason FROM offices
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY is_main DESC, name
`

func (q *Queries) ListOffices(ctx context.Context, tenantID uuid.UUID) ([]Office, error) {
	rows, err := q.db.Query(ctx, listOffices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Office
	for rows.Next() {
		var i Office
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.IsMain,
			&i.Address,
			&i.Town,
			&i.Phone,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOffice = `-- name: PurgeOffice :exec
DELETE FROM offices WHERE id = $1 AND tenant_id = $2
`

type PurgeOfficeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) PurgeOffice(ctx context.Context, arg PurgeOfficeParams) error {
	_, err := q.db.Exec(ctx, purgeOffice, arg.ID, arg.TenantID)
	return err
}

const restoreOffice = `-- name: RestoreOffice :exec
UPDATE offices SET deleted_at = NULL, deleted_by_name = '', delete_reason = ''
WHERE id = $1 AND tenant_id = $2
`

type RestoreOfficeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RestoreOffice(ctx context.Context, arg RestoreOfficeParams) error {
	_, err := q.db.Exec(ctx, restoreOffice, arg.ID, arg.TenantID)
	return err
}

const updateOffice = `-- name: UpdateOffice :one
UPDATE offices SET name = $3, code = $4, is_main = $5, address = $6, town = $7, phone = $8, email = $9, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, code, is_main, address, town, phone, email, created_at, updated_at, created_by_name, deleted_at, deleted_by_name, delete_reason
`

type UpdateOfficeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Code     string    `json:"code"`
	IsMain   bool      `json:"is_main"`
	Address  string    `json:"address"`
	Town     string    `json:"town"`
	Phone    string    `json:"phone"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateOffice(ctx context.Context, arg UpdateOfficeParams) (Office, error) {
	row := q.db.QueryRow(ctx, updateOffice,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.IsMain,
		arg.Address,
		arg.Town,
		arg.Phone,
		arg.Email,
	)
	var i Office
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.IsMain,
		&i.Address,
		&i.Town,
		&i.Phone,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByName,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
