// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_branches.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO partner_branches (tenant_id, partner_id, name, town, phone, email, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, partner_id, name, town, phone, email, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type CreateBranchParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Name          string    `json:"name"`
	Town          string    `json:"town"`
	Phone         string    `json:"phone"`
	Email         string    `json:"email"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (PartnerBranch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.TenantID,
		arg.PartnerID,
		arg.Name,
		arg.Town,
		arg.Phone,
		arg.Email,
		arg.CreatedByName,
	)
	var i PartnerBranch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.Name,
		&i.Town,
		&i.Phone,
		&i.Email,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
UPDATE partner_branches SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteBranchParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteBranch(ctx context.Context, arg DeleteBranchParams) error {
	_, err := q.db.Exec(ctx, deleteBranch,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const listBranchesByPartner = `-- name: ListBranchesByPartner :many
SELECT id, tenant_id, partner_id, name, town, phone, email, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason FROM partner_branches
WHERE partner_id = $1 AND tenant_id = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListBranchesByPartnerParams struct {
	PartnerID uuid.UUID `json:"partner_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListBranchesByPartner(ctx context.Context, arg ListBranchesByPartnerParams) ([]PartnerBranch, error) {
	rows, err := q.db.Query(ctx, listBranchesByPartner, arg.PartnerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerBranch
	for rows.Next() {
		var i PartnerBranch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartnerID,
			&i.Name,
			&i.Town,
			&i.Phone,
			&i.Email,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeBranch = `-- name: PurgeBranch :exec
DELETE FROM partner_branches WHERE id = $1 AND tenant_id = $2
`

type PurgeBranchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) PurgeBranch(ctx context.Context, arg PurgeBranchParams) error {
	_, err := q.db.Exec(ctx, purgeBranch, arg.ID, arg.TenantID)
	return err
}

const restoreBranch = `-- name: RestoreBranch :exec
UPDATE partner_branches SET deleted_at = NULL, deleted_by_name = '', delete_reason = ''
WHERE id = $1 AND tenant_id = $2
`

type RestoreBranchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RestoreBranch(ctx context.Context, arg RestoreBranchParams) error {
	_, err := q.db.Exec(ctx, restoreBranch, arg.ID, arg.TenantID)
	return err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE partner_branches SET
    name = $3,
    town = $4,
    phone = $5,
    email = $6,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, partner_id, name, town, phone, email, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type UpdateBranchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Town     string    `json:"town"`
	Phone    string    `json:"phone"`
	Email    string    `json:"email"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (PartnerBranch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Town,
		arg.Phone,
		arg.Email,
	)
	var i PartnerBranch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.Name,
		&i.Town,
		&i.Phone,
		&i.Email,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
