// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_appendix_templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAppendixTemplate = `-- name: CreateAppendixTemplate :one
INSERT INTO partner_appendix_templates (tenant_id, partner_id, name, description, fields, sort_order, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, partner_id, name, description, fields, sort_order, active, created_by_name, created_at
`

type CreateAppendixTemplateParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Fields        []byte    `json:"fields"`
	SortOrder     int32     `json:"sort_order"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateAppendixTemplate(ctx context.Context, arg CreateAppendixTemplateParams) (PartnerAppendixTemplate, error) {
	row := q.db.QueryRow(ctx, createAppendixTemplate,
		arg.TenantID,
		arg.PartnerID,
		arg.Name,
		arg.Description,
		arg.Fields,
		arg.SortOrder,
		arg.CreatedByName,
	)
	var i PartnerAppendixTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.Name,
		&i.Description,
		&i.Fields,
		&i.SortOrder,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAppendixTemplate = `-- name: DeleteAppendixTemplate :exec
UPDATE partner_appendix_templates SET active = false WHERE id = $1 AND tenant_id = $2
`

type DeleteAppendixTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAppendixTemplate(ctx context.Context, arg DeleteAppendixTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteAppendixTemplate, arg.ID, arg.TenantID)
	return err
}

const listAppendixTemplatesForPartner = `-- name: ListAppendixTemplatesForPartner :many
SELECT id, tenant_id, partner_id, name, description, fields, sort_order, active, created_by_name, created_at FROM partner_appendix_templates
WHERE partner_id = $1 AND tenant_id = $2 AND active = true
ORDER BY sort_order, created_at
`

type ListAppendixTemplatesForPartnerParams struct {
	PartnerID uuid.UUID `json:"partner_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListAppendixTemplatesForPartner(ctx context.Context, arg ListAppendixTemplatesForPartnerParams) ([]PartnerAppendixTemplate, error) {
	rows, err := q.db.Query(ctx, listAppendixTemplatesForPartner, arg.PartnerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerAppendixTemplate
	for rows.Next() {
		var i PartnerAppendixTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartnerID,
			&i.Name,
			&i.Description,
			&i.Fields,
			&i.SortOrder,
			&i.Active,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppendixTemplate = `-- name: UpdateAppendixTemplate :one
UPDATE partner_appendix_templates SET
    name = $3,
    description = $4,
    fields = $5,
    sort_order = $6
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, partner_id, name, description, fields, sort_order, active, created_by_name, created_at
`

type UpdateAppendixTemplateParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Fields      []byte    `json:"fields"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) UpdateAppendixTemplate(ctx context.Context, arg UpdateAppendixTemplateParams) (PartnerAppendixTemplate, error) {
	row := q.db.QueryRow(ctx, updateAppendixTemplate,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Fields,
		arg.SortOrder,
	)
	var i PartnerAppendixTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.Name,
		&i.Description,
		&i.Fields,
		&i.SortOrder,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}
