// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partners.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPartners = `-- name: CountPartners :one
SELECT count(*) FROM partners
WHERE tenant_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR type = $3)
  AND (
    $4::text = '' OR
    name ILIKE '%' || $4 || '%' OR
    work_email ILIKE '%' || $4 || '%' OR
    contact_name ILIKE '%' || $4 || '%'
  )
`

type CountPartnersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
}

func (q *Queries) CountPartners(ctx context.Context, arg CountPartnersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartners,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (
    tenant_id, name, logo_url, industry, partnership_model, status,
    address, town, country,
    contact_name, contact_title, work_email,
    phone_mobile, phone_office, notes, created_by_name,
    code, sla_days, default_template_id, mileage_rate_per_km, type
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16,
    $17, $18, $19, $20, $21
)
RETURNING id, tenant_id, name, logo_url, industry, partnership_model, status, address, town, country, contact_name, contact_title, work_email, phone_mobile, phone_office, notes, code, type, sla_days, default_template_id, mileage_rate_per_km, comp_min_count, comp_max_age_months, comp_max_radius_km, comp_max_variance_pct, comp_actual_sales_only, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type CreatePartnerParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	Name              string      `json:"name"`
	LogoUrl           string      `json:"logo_url"`
	Industry          string      `json:"industry"`
	PartnershipModel  string      `json:"partnership_model"`
	Status            string      `json:"status"`
	Address           string      `json:"address"`
	Town              string      `json:"town"`
	Country           string      `json:"country"`
	ContactName       string      `json:"contact_name"`
	ContactTitle      string      `json:"contact_title"`
	WorkEmail         string      `json:"work_email"`
	PhoneMobile       string      `json:"phone_mobile"`
	PhoneOffice       string      `json:"phone_office"`
	Notes             string      `json:"notes"`
	CreatedByName     string      `json:"created_by_name"`
	Code              string      `json:"code"`
	SlaDays           int32       `json:"sla_days"`
	DefaultTemplateID pgtype.UUID `json:"default_template_id"`
	MileageRatePerKm  int64       `json:"mileage_rate_per_km"`
	Type              string      `json:"type"`
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, createPartner,
		arg.TenantID,
		arg.Name,
		arg.LogoUrl,
		arg.Industry,
		arg.PartnershipModel,
		arg.Status,
		arg.Address,
		arg.Town,
		arg.Country,
		arg.ContactName,
		arg.ContactTitle,
		arg.WorkEmail,
		arg.PhoneMobile,
		arg.PhoneOffice,
		arg.Notes,
		arg.CreatedByName,
		arg.Code,
		arg.SlaDays,
		arg.DefaultTemplateID,
		arg.MileageRatePerKm,
		arg.Type,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.LogoUrl,
		&i.Industry,
		&i.PartnershipModel,
		&i.Status,
		&i.Address,
		&i.Town,
		&i.Country,
		&i.ContactName,
		&i.ContactTitle,
		&i.WorkEmail,
		&i.PhoneMobile,
		&i.PhoneOffice,
		&i.Notes,
		&i.Code,
		&i.Type,
		&i.SlaDays,
		&i.DefaultTemplateID,
		&i.MileageRatePerKm,
		&i.CompMinCount,
		&i.CompMaxAgeMonths,
		&i.CompMaxRadiusKm,
		&i.CompMaxVariancePct,
		&i.CompActualSalesOnly,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const deletePartner = `-- name: DeletePartner :exec
UPDATE partners SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeletePartnerParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeletePartner(ctx context.Context, arg DeletePartnerParams) error {
	_, err := q.db.Exec(ctx, deletePartner,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const getPartner = `-- name: GetPartner :one
SELECT id, tenant_id, name, logo_url, industry, partnership_model, status, address, town, country, contact_name, contact_title, work_email, phone_mobile, phone_office, notes, code, type, sla_days, default_template_id, mileage_rate_per_km, comp_min_count, comp_max_age_months, comp_max_radius_km, comp_max_variance_pct, comp_actual_sales_only, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason FROM partners WHERE id = $1 AND tenant_id = $2
`

type GetPartnerParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPartner(ctx context.Context, arg GetPartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, getPartner, arg.ID, arg.TenantID)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.LogoUrl,
		&i.Industry,
		&i.PartnershipModel,
		&i.Status,
		&i.Address,
		&i.Town,
		&i.Country,
		&i.ContactName,
		&i.ContactTitle,
		&i.WorkEmail,
		&i.PhoneMobile,
		&i.PhoneOffice,
		&i.Notes,
		&i.Code,
		&i.Type,
		&i.SlaDays,
		&i.DefaultTemplateID,
		&i.MileageRatePerKm,
		&i.CompMinCount,
		&i.CompMaxAgeMonths,
		&i.CompMaxRadiusKm,
		&i.CompMaxVariancePct,
		&i.CompActualSalesOnly,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const listPartners = `-- name: ListPartners :many
SELECT id, tenant_id, name, logo_url, industry, partnership_model, status, address, town, country, contact_name, contact_title, work_email, phone_mobile, phone_office, notes, code, type, sla_days, default_template_id, mileage_rate_per_km, comp_min_count, comp_max_age_months, comp_max_radius_km, comp_max_variance_pct, comp_actual_sales_only, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason FROM partners
WHERE tenant_id = $1 AND deleted_at IS NULL
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR type = $3)
  AND (
    $4::text = '' OR
    name ILIKE '%' || $4 || '%' OR
    work_email ILIKE '%' || $4 || '%' OR
    contact_name ILIKE '%' || $4 || '%'
  )
ORDER BY name
LIMIT $5 OFFSET $6
`

type ListPartnersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Column4  string    `json:"column_4"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPartners(ctx context.Context, arg ListPartnersParams) ([]Partner, error) {
	rows, err := q.db.Query(ctx, listPartners,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partner
	for rows.Next() {
		var i Partner
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.LogoUrl,
			&i.Industry,
			&i.PartnershipModel,
			&i.Status,
			&i.Address,
			&i.Town,
			&i.Country,
			&i.ContactName,
			&i.ContactTitle,
			&i.WorkEmail,
			&i.PhoneMobile,
			&i.PhoneOffice,
			&i.Notes,
			&i.Code,
			&i.Type,
			&i.SlaDays,
			&i.DefaultTemplateID,
			&i.MileageRatePerKm,
			&i.CompMinCount,
			&i.CompMaxAgeMonths,
			&i.CompMaxRadiusKm,
			&i.CompMaxVariancePct,
			&i.CompActualSalesOnly,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.DeleteReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPartnerComparableRules = `-- name: SetPartnerComparableRules :exec
UPDATE partners SET
    comp_min_count = $3,
    comp_max_age_months = $4,
    comp_max_radius_km = $5,
    comp_max_variance_pct = $6,
    comp_actual_sales_only = $7,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetPartnerComparableRulesParams struct {
	ID                  uuid.UUID `json:"id"`
	TenantID            uuid.UUID `json:"tenant_id"`
	CompMinCount        int32     `json:"comp_min_count"`
	CompMaxAgeMonths    int32     `json:"comp_max_age_months"`
	CompMaxRadiusKm     int32     `json:"comp_max_radius_km"`
	CompMaxVariancePct  int32     `json:"comp_max_variance_pct"`
	CompActualSalesOnly bool      `json:"comp_actual_sales_only"`
}

func (q *Queries) SetPartnerComparableRules(ctx context.Context, arg SetPartnerComparableRulesParams) error {
	_, err := q.db.Exec(ctx, setPartnerComparableRules,
		arg.ID,
		arg.TenantID,
		arg.CompMinCount,
		arg.CompMaxAgeMonths,
		arg.CompMaxRadiusKm,
		arg.CompMaxVariancePct,
		arg.CompActualSalesOnly,
	)
	return err
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE partners SET
    name = $3,
    logo_url = $4,
    industry = $5,
    partnership_model = $6,
    status = $7,
    address = $8,
    town = $9,
    country = $10,
    contact_name = $11,
    contact_title = $12,
    work_email = $13,
    phone_mobile = $14,
    phone_office = $15,
    notes = $16,
    code = $17,
    sla_days = $18,
    default_template_id = $19,
    mileage_rate_per_km = $20,
    type = $21,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, logo_url, industry, partnership_model, status, address, town, country, contact_name, contact_title, work_email, phone_mobile, phone_office, notes, code, type, sla_days, default_template_id, mileage_rate_per_km, comp_min_count, comp_max_age_months, comp_max_radius_km, comp_max_variance_pct, comp_actual_sales_only, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type UpdatePartnerParams struct {
	ID                uuid.UUID   `json:"id"`
	TenantID          uuid.UUID   `json:"tenant_id"`
	Name              string      `json:"name"`
	LogoUrl           string      `json:"logo_url"`
	Industry          string      `json:"industry"`
	PartnershipModel  string      `json:"partnership_model"`
	Status            string      `json:"status"`
	Address           string      `json:"address"`
	Town              string      `json:"town"`
	Country           string      `json:"country"`
	ContactName       string      `json:"contact_name"`
	ContactTitle      string      `json:"contact_title"`
	WorkEmail         string      `json:"work_email"`
	PhoneMobile       string      `json:"phone_mobile"`
	PhoneOffice       string      `json:"phone_office"`
	Notes             string      `json:"notes"`
	Code              string      `json:"code"`
	SlaDays           int32       `json:"sla_days"`
	DefaultTemplateID pgtype.UUID `json:"default_template_id"`
	MileageRatePerKm  int64       `json:"mileage_rate_per_km"`
	Type              string      `json:"type"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (Partner, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.LogoUrl,
		arg.Industry,
		arg.PartnershipModel,
		arg.Status,
		arg.Address,
		arg.Town,
		arg.Country,
		arg.ContactName,
		arg.ContactTitle,
		arg.WorkEmail,
		arg.PhoneMobile,
		arg.PhoneOffice,
		arg.Notes,
		arg.Code,
		arg.SlaDays,
		arg.DefaultTemplateID,
		arg.MileageRatePerKm,
		arg.Type,
	)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.LogoUrl,
		&i.Industry,
		&i.PartnershipModel,
		&i.Status,
		&i.Address,
		&i.Town,
		&i.Country,
		&i.ContactName,
		&i.ContactTitle,
		&i.WorkEmail,
		&i.PhoneMobile,
		&i.PhoneOffice,
		&i.Notes,
		&i.Code,
		&i.Type,
		&i.SlaDays,
		&i.DefaultTemplateID,
		&i.MileageRatePerKm,
		&i.CompMinCount,
		&i.CompMaxAgeMonths,
		&i.CompMaxRadiusKm,
		&i.CompMaxVariancePct,
		&i.CompActualSalesOnly,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}
