// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_contacts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPartnerContact = `-- name: CreatePartnerContact :one
INSERT INTO partner_contacts (
    tenant_id, partner_id, first_name, middle_name, last_name, title,
    email, phone, whatsapp, preferred_channel, is_active, inactive_reason, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, tenant_id, partner_id, first_name, middle_name, last_name, title,
          email, phone, whatsapp, preferred_channel, is_active, inactive_reason,
          created_at, created_by_name
`

type CreatePartnerContactParams struct {
	TenantID         uuid.UUID `json:"tenant_id"`
	PartnerID        uuid.UUID `json:"partner_id"`
	FirstName        string    `json:"first_name"`
	MiddleName       string    `json:"middle_name"`
	LastName         string    `json:"last_name"`
	Title            string    `json:"title"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Whatsapp         string    `json:"whatsapp"`
	PreferredChannel string    `json:"preferred_channel"`
	IsActive         bool      `json:"is_active"`
	InactiveReason   string    `json:"inactive_reason"`
	CreatedByName    string    `json:"created_by_name"`
}

type CreatePartnerContactRow struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	PartnerID        uuid.UUID `json:"partner_id"`
	FirstName        string    `json:"first_name"`
	MiddleName       string    `json:"middle_name"`
	LastName         string    `json:"last_name"`
	Title            string    `json:"title"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Whatsapp         string    `json:"whatsapp"`
	PreferredChannel string    `json:"preferred_channel"`
	IsActive         bool      `json:"is_active"`
	InactiveReason   string    `json:"inactive_reason"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedByName    string    `json:"created_by_name"`
}

func (q *Queries) CreatePartnerContact(ctx context.Context, arg CreatePartnerContactParams) (CreatePartnerContactRow, error) {
	row := q.db.QueryRow(ctx, createPartnerContact,
		arg.TenantID,
		arg.PartnerID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Title,
		arg.Email,
		arg.Phone,
		arg.Whatsapp,
		arg.PreferredChannel,
		arg.IsActive,
		arg.InactiveReason,
		arg.CreatedByName,
	)
	var i CreatePartnerContactRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Title,
		&i.Email,
		&i.Phone,
		&i.Whatsapp,
		&i.PreferredChannel,
		&i.IsActive,
		&i.InactiveReason,
		&i.CreatedAt,
		&i.CreatedByName,
	)
	return i, err
}

const deletePartnerContact = `-- name: DeletePartnerContact :exec
UPDATE partner_contacts SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeletePartnerContactParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeletePartnerContact(ctx context.Context, arg DeletePartnerContactParams) error {
	_, err := q.db.Exec(ctx, deletePartnerContact,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const listContactsByPartner = `-- name: ListContactsByPartner :many

SELECT id, tenant_id, partner_id, first_name, middle_name, last_name, title,
       email, phone, whatsapp, preferred_channel, is_active, inactive_reason,
       created_at, created_by_name
FROM partner_contacts
WHERE partner_id = $1 AND tenant_id = $2 AND deleted_at IS NULL
ORDER BY is_active DESC, last_name, first_name
`

type ListContactsByPartnerParams struct {
	PartnerID uuid.UUID `json:"partner_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

type ListContactsByPartnerRow struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	PartnerID        uuid.UUID `json:"partner_id"`
	FirstName        string    `json:"first_name"`
	MiddleName       string    `json:"middle_name"`
	LastName         string    `json:"last_name"`
	Title            string    `json:"title"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Whatsapp         string    `json:"whatsapp"`
	PreferredChannel string    `json:"preferred_channel"`
	IsActive         bool      `json:"is_active"`
	InactiveReason   string    `json:"inactive_reason"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedByName    string    `json:"created_by_name"`
}

// Partner contact persons. Distinct from MojaCRM's `contacts` table
// (Directory module, belongs to customers) — see 0006_clients_partners.up.sql.
// Explicit column lists keep deleted_* (internal audit) out of returned rows.
func (q *Queries) ListContactsByPartner(ctx context.Context, arg ListContactsByPartnerParams) ([]ListContactsByPartnerRow, error) {
	rows, err := q.db.Query(ctx, listContactsByPartner, arg.PartnerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsByPartnerRow
	for rows.Next() {
		var i ListContactsByPartnerRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartnerID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.Title,
			&i.Email,
			&i.Phone,
			&i.Whatsapp,
			&i.PreferredChannel,
			&i.IsActive,
			&i.InactiveReason,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartnerContact = `-- name: UpdatePartnerContact :one
UPDATE partner_contacts SET
    first_name = $3,
    middle_name = $4,
    last_name = $5,
    title = $6,
    email = $7,
    phone = $8,
    whatsapp = $9,
    preferred_channel = $10,
    is_active = $11,
    inactive_reason = $12,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, partner_id, first_name, middle_name, last_name, title,
          email, phone, whatsapp, preferred_channel, is_active, inactive_reason,
          created_at, created_by_name
`

type UpdatePartnerContactParams struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	FirstName        string    `json:"first_name"`
	MiddleName       string    `json:"middle_name"`
	LastName         string    `json:"last_name"`
	Title            string    `json:"title"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Whatsapp         string    `json:"whatsapp"`
	PreferredChannel string    `json:"preferred_channel"`
	IsActive         bool      `json:"is_active"`
	InactiveReason   string    `json:"inactive_reason"`
}

type UpdatePartnerContactRow struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	PartnerID        uuid.UUID `json:"partner_id"`
	FirstName        string    `json:"first_name"`
	MiddleName       string    `json:"middle_name"`
	LastName         string    `json:"last_name"`
	Title            string    `json:"title"`
	Email            string    `json:"email"`
	Phone            string    `json:"phone"`
	Whatsapp         string    `json:"whatsapp"`
	PreferredChannel string    `json:"preferred_channel"`
	IsActive         bool      `json:"is_active"`
	InactiveReason   string    `json:"inactive_reason"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedByName    string    `json:"created_by_name"`
}

func (q *Queries) UpdatePartnerContact(ctx context.Context, arg UpdatePartnerContactParams) (UpdatePartnerContactRow, error) {
	row := q.db.QueryRow(ctx, updatePartnerContact,
		arg.ID,
		arg.TenantID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.Title,
		arg.Email,
		arg.Phone,
		arg.Whatsapp,
		arg.PreferredChannel,
		arg.IsActive,
		arg.InactiveReason,
	)
	var i UpdatePartnerContactRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.Title,
		&i.Email,
		&i.Phone,
		&i.Whatsapp,
		&i.PreferredChannel,
		&i.IsActive,
		&i.InactiveReason,
		&i.CreatedAt,
		&i.CreatedByName,
	)
	return i, err
}
