// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partner_requirements.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPartnerRequirement = `-- name: CreatePartnerRequirement :one
INSERT INTO partner_requirements (tenant_id, partner_id, label, detail, kind, sort_order, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, partner_id, label, detail, kind, sort_order, active, created_by_name, created_at
`

type CreatePartnerRequirementParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	PartnerID     uuid.UUID `json:"partner_id"`
	Label         string    `json:"label"`
	Detail        string    `json:"detail"`
	Kind          string    `json:"kind"`
	SortOrder     int32     `json:"sort_order"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreatePartnerRequirement(ctx context.Context, arg CreatePartnerRequirementParams) (PartnerRequirement, error) {
	row := q.db.QueryRow(ctx, createPartnerRequirement,
		arg.TenantID,
		arg.PartnerID,
		arg.Label,
		arg.Detail,
		arg.Kind,
		arg.SortOrder,
		arg.CreatedByName,
	)
	var i PartnerRequirement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartnerID,
		&i.Label,
		&i.Detail,
		&i.Kind,
		&i.SortOrder,
		&i.Active,
		&i.CreatedByName,
		&i.CreatedAt,
	)
	return i, err
}

const deletePartnerRequirement = `-- name: DeletePartnerRequirement :exec
UPDATE partner_requirements SET active = false WHERE id = $1 AND tenant_id = $2
`

type DeletePartnerRequirementParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePartnerRequirement(ctx context.Context, arg DeletePartnerRequirementParams) error {
	_, err := q.db.Exec(ctx, deletePartnerRequirement, arg.ID, arg.TenantID)
	return err
}

const listPartnerRequirements = `-- name: ListPartnerRequirements :many

SELECT id, tenant_id, partner_id, label, detail, kind, sort_order, active, created_by_name, created_at FROM partner_requirements
WHERE partner_id = $1 AND tenant_id = $2 AND active = true
ORDER BY sort_order, created_at
`

type ListPartnerRequirementsParams struct {
	PartnerID uuid.UUID `json:"partner_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

// Per-partner requirement packs. Job-level completion tracking
// (instruction_requirement_status in propsense) is out of scope here since
// MojaCRM has no `instructions` table yet — see 0006_clients_partners.up.sql.
func (q *Queries) ListPartnerRequirements(ctx context.Context, arg ListPartnerRequirementsParams) ([]PartnerRequirement, error) {
	rows, err := q.db.Query(ctx, listPartnerRequirements, arg.PartnerID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerRequirement
	for rows.Next() {
		var i PartnerRequirement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartnerID,
			&i.Label,
			&i.Detail,
			&i.Kind,
			&i.SortOrder,
			&i.Active,
			&i.CreatedByName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartnerRequirement = `-- name: UpdatePartnerRequirement :exec
UPDATE partner_requirements SET label = $3, detail = $4, kind = $5, sort_order = $6
WHERE id = $1 AND tenant_id = $2
`

type UpdatePartnerRequirementParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Label     string    `json:"label"`
	Detail    string    `json:"detail"`
	Kind      string    `json:"kind"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) UpdatePartnerRequirement(ctx context.Context, arg UpdatePartnerRequirementParams) error {
	_, err := q.db.Exec(ctx, updatePartnerRequirement,
		arg.ID,
		arg.TenantID,
		arg.Label,
		arg.Detail,
		arg.Kind,
		arg.SortOrder,
	)
	return err
}
