// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admins (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, status, created_at
`

type CreatePlatformAdminParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin, arg.Email, arg.Name, arg.PasswordHash)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByEmail = `-- name: GetPlatformAdminByEmail :one
SELECT id, email, name, password_hash, status, created_at FROM platform_admins WHERE email = $1
`

func (q *Queries) GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, email, name, password_hash, status, created_at FROM platform_admins WHERE id = $1
`

func (q *Queries) GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatformAdmins = `-- name: ListPlatformAdmins :many
SELECT id, email, name, password_hash, status, created_at FROM platform_admins ORDER BY created_at ASC
`

func (q *Queries) ListPlatformAdmins(ctx context.Context) ([]PlatformAdmin, error) {
	rows, err := q.db.Query(ctx, listPlatformAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlatformAdmin
	for rows.Next() {
		var i PlatformAdmin
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
