// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_settings.sql

package db

import (
	"context"
)

const getPlatformSettings = `-- name: GetPlatformSettings :one
SELECT id, app_name, tagline, logo_url, icon_url, updated_at FROM platform_settings WHERE id = true
`

func (q *Queries) GetPlatformSettings(ctx context.Context) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, getPlatformSettings)
	var i PlatformSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Tagline,
		&i.LogoUrl,
		&i.IconUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlatformSettings = `-- name: UpdatePlatformSettings :one
UPDATE platform_settings SET
    app_name = $1,
    tagline = $2,
    logo_url = $3,
    icon_url = $4,
    updated_at = now()
WHERE id = true
RETURNING id, app_name, tagline, logo_url, icon_url, updated_at
`

type UpdatePlatformSettingsParams struct {
	AppName string `json:"app_name"`
	Tagline string `json:"tagline"`
	LogoUrl string `json:"logo_url"`
	IconUrl string `json:"icon_url"`
}

func (q *Queries) UpdatePlatformSettings(ctx context.Context, arg UpdatePlatformSettingsParams) (PlatformSetting, error) {
	row := q.db.QueryRow(ctx, updatePlatformSettings,
		arg.AppName,
		arg.Tagline,
		arg.LogoUrl,
		arg.IconUrl,
	)
	var i PlatformSetting
	err := row.Scan(
		&i.ID,
		&i.AppName,
		&i.Tagline,
		&i.LogoUrl,
		&i.IconUrl,
		&i.UpdatedAt,
	)
	return i, err
}
