// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	AddTagToCustomer(ctx context.Context, arg AddTagToCustomerParams) error
	ArchiveCustomer(ctx context.Context, arg ArchiveCustomerParams) (Customer, error)
	AssignAccountOwner(ctx context.Context, arg AssignAccountOwnerParams) (Customer, error)
	ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	CompleteFollowUp(ctx context.Context, arg CompleteFollowUpParams) (CustomerCommunication, error)
	CountCommunications(ctx context.Context, arg CountCommunicationsParams) (int64, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	CreateCommunication(ctx context.Context, arg CreateCommunicationParams) (CustomerCommunication, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerNote(ctx context.Context, arg CreateCustomerNoteParams) (CustomerNote, error)
	CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCommunication(ctx context.Context, arg DeleteCommunicationParams) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetCommunicationByID(ctx context.Context, arg GetCommunicationByIDParams) (CustomerCommunication, error)
	GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (GetCustomerByIDRow, error)
	GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error)
	GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error)
	GetPlatformSettings(ctx context.Context) (PlatformSetting, error)
	GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByEmailAnyTenant(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByVerificationToken(ctx context.Context, verificationToken *string) (User, error)
	GetUserPermissionKeys(ctx context.Context, id uuid.UUID) ([]string, error)
	GetUserWithRoleByID(ctx context.Context, id uuid.UUID) (GetUserWithRoleByIDRow, error)
	ListCommunications(ctx context.Context, arg ListCommunicationsParams) ([]ListCommunicationsRow, error)
	ListCommunicationsByCustomer(ctx context.Context, customerID uuid.UUID) ([]ListCommunicationsByCustomerRow, error)
	ListContactsByCustomer(ctx context.Context, customerID uuid.UUID) ([]Contact, error)
	ListCustomerNotes(ctx context.Context, customerID uuid.UUID) ([]ListCustomerNotesRow, error)
	ListCustomerTags(ctx context.Context, customerID uuid.UUID) ([]Tag, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error)
	ListFollowUpsDue(ctx context.Context, tenantID uuid.UUID) ([]ListFollowUpsDueRow, error)
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListPlatformAdmins(ctx context.Context) ([]PlatformAdmin, error)
	ListRolePermissionKeys(ctx context.Context, roleID uuid.UUID) ([]string, error)
	ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error)
	ListTags(ctx context.Context, tenantID uuid.UUID) ([]Tag, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsersWithRole(ctx context.Context, tenantID uuid.UUID) ([]ListUsersWithRoleRow, error)
	MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error)
	RemoveTagFromCustomer(ctx context.Context, arg RemoveTagFromCustomerParams) error
	RestoreCustomer(ctx context.Context, arg RestoreCustomerParams) (Customer, error)
	SetContactPrimary(ctx context.Context, arg SetContactPrimaryParams) (Contact, error)
	SetContactStatus(ctx context.Context, arg SetContactStatusParams) (Contact, error)
	SetCustomerStatus(ctx context.Context, arg SetCustomerStatusParams) (Customer, error)
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error)
	SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error
	UnsetPrimaryContacts(ctx context.Context, customerID uuid.UUID) error
	UpdateCommunicationStatus(ctx context.Context, arg UpdateCommunicationStatusParams) (CustomerCommunication, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdatePlatformSettings(ctx context.Context, arg UpdatePlatformSettingsParams) (PlatformSetting, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
