// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference_data.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createReferenceData = `-- name: CreateReferenceData :one
INSERT INTO reference_data (tenant_id, category, value, label, sort_order, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, category, value, label, sort_order, created_by_name, created_at, deleted_at
`

type CreateReferenceDataParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	Category      string    `json:"category"`
	Value         string    `json:"value"`
	Label         string    `json:"label"`
	SortOrder     int32     `json:"sort_order"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) CreateReferenceData(ctx context.Context, arg CreateReferenceDataParams) (ReferenceDatum, error) {
	row := q.db.QueryRow(ctx, createReferenceData,
		arg.TenantID,
		arg.Category,
		arg.Value,
		arg.Label,
		arg.SortOrder,
		arg.CreatedByName,
	)
	var i ReferenceDatum
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Category,
		&i.Value,
		&i.Label,
		&i.SortOrder,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteReferenceData = `-- name: DeleteReferenceData :exec
UPDATE reference_data SET deleted_at = now() WHERE id = $1 AND tenant_id = $2
`

type DeleteReferenceDataParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteReferenceData(ctx context.Context, arg DeleteReferenceDataParams) error {
	_, err := q.db.Exec(ctx, deleteReferenceData, arg.ID, arg.TenantID)
	return err
}

const listReferenceData = `-- name: ListReferenceData :many
SELECT id, tenant_id, category, value, label, sort_order, created_by_name, created_at, deleted_at FROM reference_data
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY category, sort_order, label, value
`

func (q *Queries) ListReferenceData(ctx context.Context, tenantID uuid.UUID) ([]ReferenceDatum, error) {
	rows, err := q.db.Query(ctx, listReferenceData, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceDatum
	for rows.Next() {
		var i ReferenceDatum
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Category,
			&i.Value,
			&i.Label,
			&i.SortOrder,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceDataByCategory = `-- name: ListReferenceDataByCategory :many
SELECT id, tenant_id, category, value, label, sort_order, created_by_name, created_at, deleted_at FROM reference_data
WHERE tenant_id = $1 AND category = $2 AND deleted_at IS NULL
ORDER BY sort_order, label, value
`

type ListReferenceDataByCategoryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Category string    `json:"category"`
}

func (q *Queries) ListReferenceDataByCategory(ctx context.Context, arg ListReferenceDataByCategoryParams) ([]ReferenceDatum, error) {
	rows, err := q.db.Query(ctx, listReferenceDataByCategory, arg.TenantID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceDatum
	for rows.Next() {
		var i ReferenceDatum
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Category,
			&i.Value,
			&i.Label,
			&i.SortOrder,
			&i.CreatedByName,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
