// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTenderDocument = `-- name: AddTenderDocument :one
INSERT INTO tender_documents (tenant_id, tender_id, name, label, kind, data_url, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type AddTenderDocumentParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	TenderID      uuid.UUID `json:"tender_id"`
	Name          string    `json:"name"`
	Label         string    `json:"label"`
	Kind          string    `json:"kind"`
	DataUrl       string    `json:"data_url"`
	CreatedByName string    `json:"created_by_name"`
}

func (q *Queries) AddTenderDocument(ctx context.Context, arg AddTenderDocumentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addTenderDocument,
		arg.TenantID,
		arg.TenderID,
		arg.Name,
		arg.Label,
		arg.Kind,
		arg.DataUrl,
		arg.CreatedByName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const assignTender = `-- name: AssignTender :exec
UPDATE tenders SET owner_user_id = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type AssignTenderParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) AssignTender(ctx context.Context, arg AssignTenderParams) error {
	_, err := q.db.Exec(ctx, assignTender, arg.ID, arg.TenantID, arg.OwnerUserID)
	return err
}

const countTenders = `-- name: CountTenders :one
SELECT count(*)
FROM tenders t
WHERE t.tenant_id = $1 AND t.deleted_at IS NULL
  AND ($2::text = '' OR t.stage = $2)
  AND (
    $3::text = '' OR
    t.title ILIKE '%' || $3 || '%' OR
    t.issuer ILIKE '%' || $3 || '%' OR
    t.reference ILIKE '%' || $3 || '%'
  )
`

type CountTendersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
}

func (q *Queries) CountTenders(ctx context.Context, arg CountTendersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenders, arg.TenantID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTender = `-- name: CreateTender :one
INSERT INTO tenders (
    tenant_id, title, reference, issuer, type, category, description, stage, outcome_note,
    submission_deadline, opening_datetime, submission_method, submission_address, submission_email, submission_contact,
    estimated_value, doc_fee, currency, security_type, security_amount, security_validity,
    owner_user_id, signed, requirements, contact_name, contact_email, notes, created_by_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26, $27, $28
)
RETURNING id, tenant_id, title, reference, issuer, type, category, description, stage, outcome_note, submission_deadline, opening_datetime, submitted_on, submission_method, submission_address, submission_email, submission_contact, estimated_value, doc_fee, currency, security_type, security_amount, security_validity, owner_user_id, signed, requirements, stage_log, submission_log, contact_name, contact_email, notes, reminded_7d_at, reminded_1d_at, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type CreateTenderParams struct {
	TenantID           uuid.UUID   `json:"tenant_id"`
	Title              string      `json:"title"`
	Reference          string      `json:"reference"`
	Issuer             string      `json:"issuer"`
	Type               string      `json:"type"`
	Category           string      `json:"category"`
	Description        string      `json:"description"`
	Stage              string      `json:"stage"`
	OutcomeNote        string      `json:"outcome_note"`
	SubmissionDeadline string      `json:"submission_deadline"`
	OpeningDatetime    string      `json:"opening_datetime"`
	SubmissionMethod   string      `json:"submission_method"`
	SubmissionAddress  string      `json:"submission_address"`
	SubmissionEmail    string      `json:"submission_email"`
	SubmissionContact  string      `json:"submission_contact"`
	EstimatedValue     int64       `json:"estimated_value"`
	DocFee             int64       `json:"doc_fee"`
	Currency           string      `json:"currency"`
	SecurityType       string      `json:"security_type"`
	SecurityAmount     int64       `json:"security_amount"`
	SecurityValidity   string      `json:"security_validity"`
	OwnerUserID        pgtype.UUID `json:"owner_user_id"`
	Signed             bool        `json:"signed"`
	Requirements       []byte      `json:"requirements"`
	ContactName        string      `json:"contact_name"`
	ContactEmail       string      `json:"contact_email"`
	Notes              string      `json:"notes"`
	CreatedByName      string      `json:"created_by_name"`
}

func (q *Queries) CreateTender(ctx context.Context, arg CreateTenderParams) (Tender, error) {
	row := q.db.QueryRow(ctx, createTender,
		arg.TenantID,
		arg.Title,
		arg.Reference,
		arg.Issuer,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.Stage,
		arg.OutcomeNote,
		arg.SubmissionDeadline,
		arg.OpeningDatetime,
		arg.SubmissionMethod,
		arg.SubmissionAddress,
		arg.SubmissionEmail,
		arg.SubmissionContact,
		arg.EstimatedValue,
		arg.DocFee,
		arg.Currency,
		arg.SecurityType,
		arg.SecurityAmount,
		arg.SecurityValidity,
		arg.OwnerUserID,
		arg.Signed,
		arg.Requirements,
		arg.ContactName,
		arg.ContactEmail,
		arg.Notes,
		arg.CreatedByName,
	)
	var i Tender
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Reference,
		&i.Issuer,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.Stage,
		&i.OutcomeNote,
		&i.SubmissionDeadline,
		&i.OpeningDatetime,
		&i.SubmittedOn,
		&i.SubmissionMethod,
		&i.SubmissionAddress,
		&i.SubmissionEmail,
		&i.SubmissionContact,
		&i.EstimatedValue,
		&i.DocFee,
		&i.Currency,
		&i.SecurityType,
		&i.SecurityAmount,
		&i.SecurityValidity,
		&i.OwnerUserID,
		&i.Signed,
		&i.Requirements,
		&i.StageLog,
		&i.SubmissionLog,
		&i.ContactName,
		&i.ContactEmail,
		&i.Notes,
		&i.Reminded7dAt,
		&i.Reminded1dAt,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const createTenderLetter = `-- name: CreateTenderLetter :one
INSERT INTO tender_letters (tenant_id, name, kind, template_content, is_default, created_by_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateTenderLetterParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	Name            string    `json:"name"`
	Kind            string    `json:"kind"`
	TemplateContent string    `json:"template_content"`
	IsDefault       bool      `json:"is_default"`
	CreatedByName   string    `json:"created_by_name"`
}

func (q *Queries) CreateTenderLetter(ctx context.Context, arg CreateTenderLetterParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTenderLetter,
		arg.TenantID,
		arg.Name,
		arg.Kind,
		arg.TemplateContent,
		arg.IsDefault,
		arg.CreatedByName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTender = `-- name: DeleteTender :exec
UPDATE tenders SET deleted_at = now(), deleted_by_name = $3, delete_reason = $4
WHERE id = $1 AND tenant_id = $2
`

type DeleteTenderParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	DeletedByName string    `json:"deleted_by_name"`
	DeleteReason  string    `json:"delete_reason"`
}

func (q *Queries) DeleteTender(ctx context.Context, arg DeleteTenderParams) error {
	_, err := q.db.Exec(ctx, deleteTender,
		arg.ID,
		arg.TenantID,
		arg.DeletedByName,
		arg.DeleteReason,
	)
	return err
}

const deleteTenderDocument = `-- name: DeleteTenderDocument :exec
DELETE FROM tender_documents WHERE id = $1 AND tenant_id = $2
`

type DeleteTenderDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTenderDocument(ctx context.Context, arg DeleteTenderDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteTenderDocument, arg.ID, arg.TenantID)
	return err
}

const deleteTenderLetter = `-- name: DeleteTenderLetter :exec
UPDATE tender_letters SET deleted_at = now() WHERE id = $1 AND tenant_id = $2
`

type DeleteTenderLetterParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTenderLetter(ctx context.Context, arg DeleteTenderLetterParams) error {
	_, err := q.db.Exec(ctx, deleteTenderLetter, arg.ID, arg.TenantID)
	return err
}

const getTender = `-- name: GetTender :one
SELECT t.id, t.tenant_id, t.title, t.reference, t.issuer, t.type, t.category, t.description, t.stage, t.outcome_note, t.submission_deadline, t.opening_datetime, t.submitted_on, t.submission_method, t.submission_address, t.submission_email, t.submission_contact, t.estimated_value, t.doc_fee, t.currency, t.security_type, t.security_amount, t.security_validity, t.owner_user_id, t.signed, t.requirements, t.stage_log, t.submission_log, t.contact_name, t.contact_email, t.notes, t.reminded_7d_at, t.reminded_1d_at, t.created_by_name, t.created_at, t.updated_at, t.deleted_at, t.deleted_by_name, t.delete_reason, COALESCE(u.name, '') AS owner_name
FROM tenders t
LEFT JOIN users u ON u.id = t.owner_user_id
WHERE t.id = $1 AND t.tenant_id = $2 AND t.deleted_at IS NULL
`

type GetTenderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetTenderRow struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           uuid.UUID          `json:"tenant_id"`
	Title              string             `json:"title"`
	Reference          string             `json:"reference"`
	Issuer             string             `json:"issuer"`
	Type               string             `json:"type"`
	Category           string             `json:"category"`
	Description        string             `json:"description"`
	Stage              string             `json:"stage"`
	OutcomeNote        string             `json:"outcome_note"`
	SubmissionDeadline string             `json:"submission_deadline"`
	OpeningDatetime    string             `json:"opening_datetime"`
	SubmittedOn        string             `json:"submitted_on"`
	SubmissionMethod   string             `json:"submission_method"`
	SubmissionAddress  string             `json:"submission_address"`
	SubmissionEmail    string             `json:"submission_email"`
	SubmissionContact  string             `json:"submission_contact"`
	EstimatedValue     int64              `json:"estimated_value"`
	DocFee             int64              `json:"doc_fee"`
	Currency           string             `json:"currency"`
	SecurityType       string             `json:"security_type"`
	SecurityAmount     int64              `json:"security_amount"`
	SecurityValidity   string             `json:"security_validity"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	Signed             bool               `json:"signed"`
	Requirements       []byte             `json:"requirements"`
	StageLog           []byte             `json:"stage_log"`
	SubmissionLog      []byte             `json:"submission_log"`
	ContactName        string             `json:"contact_name"`
	ContactEmail       string             `json:"contact_email"`
	Notes              string             `json:"notes"`
	Reminded7dAt       pgtype.Timestamptz `json:"reminded_7d_at"`
	Reminded1dAt       pgtype.Timestamptz `json:"reminded_1d_at"`
	CreatedByName      string             `json:"created_by_name"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName      string             `json:"deleted_by_name"`
	DeleteReason       string             `json:"delete_reason"`
	OwnerName          string             `json:"owner_name"`
}

func (q *Queries) GetTender(ctx context.Context, arg GetTenderParams) (GetTenderRow, error) {
	row := q.db.QueryRow(ctx, getTender, arg.ID, arg.TenantID)
	var i GetTenderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Reference,
		&i.Issuer,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.Stage,
		&i.OutcomeNote,
		&i.SubmissionDeadline,
		&i.OpeningDatetime,
		&i.SubmittedOn,
		&i.SubmissionMethod,
		&i.SubmissionAddress,
		&i.SubmissionEmail,
		&i.SubmissionContact,
		&i.EstimatedValue,
		&i.DocFee,
		&i.Currency,
		&i.SecurityType,
		&i.SecurityAmount,
		&i.SecurityValidity,
		&i.OwnerUserID,
		&i.Signed,
		&i.Requirements,
		&i.StageLog,
		&i.SubmissionLog,
		&i.ContactName,
		&i.ContactEmail,
		&i.Notes,
		&i.Reminded7dAt,
		&i.Reminded1dAt,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
		&i.OwnerName,
	)
	return i, err
}

const getTenderDocument = `-- name: GetTenderDocument :one
SELECT id, data_url, name FROM tender_documents WHERE id = $1 AND tenant_id = $2
`

type GetTenderDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetTenderDocumentRow struct {
	ID      uuid.UUID `json:"id"`
	DataUrl string    `json:"data_url"`
	Name    string    `json:"name"`
}

func (q *Queries) GetTenderDocument(ctx context.Context, arg GetTenderDocumentParams) (GetTenderDocumentRow, error) {
	row := q.db.QueryRow(ctx, getTenderDocument, arg.ID, arg.TenantID)
	var i GetTenderDocumentRow
	err := row.Scan(&i.ID, &i.DataUrl, &i.Name)
	return i, err
}

const listTenderDocuments = `-- name: ListTenderDocuments :many

SELECT id, name, label, kind, created_at, created_by_name
FROM tender_documents WHERE tender_id = $1 AND tenant_id = $2 ORDER BY created_at
`

type ListTenderDocumentsParams struct {
	TenderID uuid.UUID `json:"tender_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTenderDocumentsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Label         string    `json:"label"`
	Kind          string    `json:"kind"`
	CreatedAt     time.Time `json:"created_at"`
	CreatedByName string    `json:"created_by_name"`
}

// ---- Documents ----
func (q *Queries) ListTenderDocuments(ctx context.Context, arg ListTenderDocumentsParams) ([]ListTenderDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listTenderDocuments, arg.TenderID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenderDocumentsRow
	for rows.Next() {
		var i ListTenderDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Label,
			&i.Kind,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenderLetters = `-- name: ListTenderLetters :many

SELECT id, name, kind, template_content, is_default, created_at, created_by_name
FROM tender_letters WHERE tenant_id = $1 AND deleted_at IS NULL ORDER BY name
`

type ListTenderLettersRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Kind            string    `json:"kind"`
	TemplateContent string    `json:"template_content"`
	IsDefault       bool      `json:"is_default"`
	CreatedAt       time.Time `json:"created_at"`
	CreatedByName   string    `json:"created_by_name"`
}

// ---- Letter templates ----
func (q *Queries) ListTenderLetters(ctx context.Context, tenantID uuid.UUID) ([]ListTenderLettersRow, error) {
	rows, err := q.db.Query(ctx, listTenderLetters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenderLettersRow
	for rows.Next() {
		var i ListTenderLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.TemplateContent,
			&i.IsDefault,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenders = `-- name: ListTenders :many

SELECT t.id, t.title, t.reference, t.issuer, t.type, t.category, t.stage,
       t.submission_deadline, t.opening_datetime, t.estimated_value, t.doc_fee, t.currency,
       t.security_type, t.security_amount, t.signed, t.submitted_on, t.outcome_note,
       t.owner_user_id, COALESCE(u.name, '') AS owner_name,
       (SELECT count(*) FROM tender_documents d WHERE d.tender_id = t.id) AS doc_count,
       t.created_at, t.created_by_name
FROM tenders t
LEFT JOIN users u ON u.id = t.owner_user_id
WHERE t.tenant_id = $1 AND t.deleted_at IS NULL
  AND ($2::text = '' OR t.stage = $2)
  AND (
    $3::text = '' OR
    t.title ILIKE '%' || $3 || '%' OR
    t.issuer ILIKE '%' || $3 || '%' OR
    t.reference ILIKE '%' || $3 || '%'
  )
ORDER BY (t.submission_deadline = '') ASC, t.submission_deadline ASC, t.created_at DESC
LIMIT $4 OFFSET $5
`

type ListTendersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  string    `json:"column_2"`
	Column3  string    `json:"column_3"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListTendersRow struct {
	ID                 uuid.UUID   `json:"id"`
	Title              string      `json:"title"`
	Reference          string      `json:"reference"`
	Issuer             string      `json:"issuer"`
	Type               string      `json:"type"`
	Category           string      `json:"category"`
	Stage              string      `json:"stage"`
	SubmissionDeadline string      `json:"submission_deadline"`
	OpeningDatetime    string      `json:"opening_datetime"`
	EstimatedValue     int64       `json:"estimated_value"`
	DocFee             int64       `json:"doc_fee"`
	Currency           string      `json:"currency"`
	SecurityType       string      `json:"security_type"`
	SecurityAmount     int64       `json:"security_amount"`
	Signed             bool        `json:"signed"`
	SubmittedOn        string      `json:"submitted_on"`
	OutcomeNote        string      `json:"outcome_note"`
	OwnerUserID        pgtype.UUID `json:"owner_user_id"`
	OwnerName          string      `json:"owner_name"`
	DocCount           int64       `json:"doc_count"`
	CreatedAt          time.Time   `json:"created_at"`
	CreatedByName      string      `json:"created_by_name"`
}

// Tenders & Pre-Qualification, ported from propsense (waterboy backend).
// propsense scopes rows via Postgres RLS + current_tenant_id(); MojaCRM has
// no RLS, so every query takes an explicit tenant_id (see clients.sql).
func (q *Queries) ListTenders(ctx context.Context, arg ListTendersParams) ([]ListTendersRow, error) {
	rows, err := q.db.Query(ctx, listTenders,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTendersRow
	for rows.Next() {
		var i ListTendersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Reference,
			&i.Issuer,
			&i.Type,
			&i.Category,
			&i.Stage,
			&i.SubmissionDeadline,
			&i.OpeningDatetime,
			&i.EstimatedValue,
			&i.DocFee,
			&i.Currency,
			&i.SecurityType,
			&i.SecurityAmount,
			&i.Signed,
			&i.SubmittedOn,
			&i.OutcomeNote,
			&i.OwnerUserID,
			&i.OwnerName,
			&i.DocCount,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeTender = `-- name: PurgeTender :exec
DELETE FROM tenders WHERE id = $1 AND tenant_id = $2
`

type PurgeTenderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) PurgeTender(ctx context.Context, arg PurgeTenderParams) error {
	_, err := q.db.Exec(ctx, purgeTender, arg.ID, arg.TenantID)
	return err
}

const restoreTender = `-- name: RestoreTender :exec
UPDATE tenders SET deleted_at = NULL, deleted_by_name = '', delete_reason = ''
WHERE id = $1 AND tenant_id = $2
`

type RestoreTenderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RestoreTender(ctx context.Context, arg RestoreTenderParams) error {
	_, err := q.db.Exec(ctx, restoreTender, arg.ID, arg.TenantID)
	return err
}

const setTenderStage = `-- name: SetTenderStage :exec
UPDATE tenders SET stage = $3, stage_log = $4, outcome_note = $5, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetTenderStageParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Stage       string    `json:"stage"`
	StageLog    []byte    `json:"stage_log"`
	OutcomeNote string    `json:"outcome_note"`
}

func (q *Queries) SetTenderStage(ctx context.Context, arg SetTenderStageParams) error {
	_, err := q.db.Exec(ctx, setTenderStage,
		arg.ID,
		arg.TenantID,
		arg.Stage,
		arg.StageLog,
		arg.OutcomeNote,
	)
	return err
}

const setTenderSubmission = `-- name: SetTenderSubmission :exec
UPDATE tenders SET stage = 'submitted', submitted_on = $3, submission_method = $4, submission_log = $5, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type SetTenderSubmissionParams struct {
	ID               uuid.UUID `json:"id"`
	TenantID         uuid.UUID `json:"tenant_id"`
	SubmittedOn      string    `json:"submitted_on"`
	SubmissionMethod string    `json:"submission_method"`
	SubmissionLog    []byte    `json:"submission_log"`
}

func (q *Queries) SetTenderSubmission(ctx context.Context, arg SetTenderSubmissionParams) error {
	_, err := q.db.Exec(ctx, setTenderSubmission,
		arg.ID,
		arg.TenantID,
		arg.SubmittedOn,
		arg.SubmissionMethod,
		arg.SubmissionLog,
	)
	return err
}

const updateTender = `-- name: UpdateTender :one
UPDATE tenders SET
    title = $3, reference = $4, issuer = $5, type = $6, category = $7, description = $8,
    stage = $9, outcome_note = $10, submission_deadline = $11, opening_datetime = $12,
    submission_method = $13, submission_address = $14, submission_email = $15, submission_contact = $16,
    estimated_value = $17, doc_fee = $18, currency = $19, security_type = $20, security_amount = $21, security_validity = $22,
    owner_user_id = $23, signed = $24, requirements = $25, contact_name = $26, contact_email = $27, notes = $28,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, reference, issuer, type, category, description, stage, outcome_note, submission_deadline, opening_datetime, submitted_on, submission_method, submission_address, submission_email, submission_contact, estimated_value, doc_fee, currency, security_type, security_amount, security_validity, owner_user_id, signed, requirements, stage_log, submission_log, contact_name, contact_email, notes, reminded_7d_at, reminded_1d_at, created_by_name, created_at, updated_at, deleted_at, deleted_by_name, delete_reason
`

type UpdateTenderParams struct {
	ID                 uuid.UUID   `json:"id"`
	TenantID           uuid.UUID   `json:"tenant_id"`
	Title              string      `json:"title"`
	Reference          string      `json:"reference"`
	Issuer             string      `json:"issuer"`
	Type               string      `json:"type"`
	Category           string      `json:"category"`
	Description        string      `json:"description"`
	Stage              string      `json:"stage"`
	OutcomeNote        string      `json:"outcome_note"`
	SubmissionDeadline string      `json:"submission_deadline"`
	OpeningDatetime    string      `json:"opening_datetime"`
	SubmissionMethod   string      `json:"submission_method"`
	SubmissionAddress  string      `json:"submission_address"`
	SubmissionEmail    string      `json:"submission_email"`
	SubmissionContact  string      `json:"submission_contact"`
	EstimatedValue     int64       `json:"estimated_value"`
	DocFee             int64       `json:"doc_fee"`
	Currency           string      `json:"currency"`
	SecurityType       string      `json:"security_type"`
	SecurityAmount     int64       `json:"security_amount"`
	SecurityValidity   string      `json:"security_validity"`
	OwnerUserID        pgtype.UUID `json:"owner_user_id"`
	Signed             bool        `json:"signed"`
	Requirements       []byte      `json:"requirements"`
	ContactName        string      `json:"contact_name"`
	ContactEmail       string      `json:"contact_email"`
	Notes              string      `json:"notes"`
}

func (q *Queries) UpdateTender(ctx context.Context, arg UpdateTenderParams) (Tender, error) {
	row := q.db.QueryRow(ctx, updateTender,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Reference,
		arg.Issuer,
		arg.Type,
		arg.Category,
		arg.Description,
		arg.Stage,
		arg.OutcomeNote,
		arg.SubmissionDeadline,
		arg.OpeningDatetime,
		arg.SubmissionMethod,
		arg.SubmissionAddress,
		arg.SubmissionEmail,
		arg.SubmissionContact,
		arg.EstimatedValue,
		arg.DocFee,
		arg.Currency,
		arg.SecurityType,
		arg.SecurityAmount,
		arg.SecurityValidity,
		arg.OwnerUserID,
		arg.Signed,
		arg.Requirements,
		arg.ContactName,
		arg.ContactEmail,
		arg.Notes,
	)
	var i Tender
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Reference,
		&i.Issuer,
		&i.Type,
		&i.Category,
		&i.Description,
		&i.Stage,
		&i.OutcomeNote,
		&i.SubmissionDeadline,
		&i.OpeningDatetime,
		&i.SubmittedOn,
		&i.SubmissionMethod,
		&i.SubmissionAddress,
		&i.SubmissionEmail,
		&i.SubmissionContact,
		&i.EstimatedValue,
		&i.DocFee,
		&i.Currency,
		&i.SecurityType,
		&i.SecurityAmount,
		&i.SecurityValidity,
		&i.OwnerUserID,
		&i.Signed,
		&i.Requirements,
		&i.StageLog,
		&i.SubmissionLog,
		&i.ContactName,
		&i.ContactEmail,
		&i.Notes,
		&i.Reminded7dAt,
		&i.Reminded1dAt,
		&i.CreatedByName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByName,
		&i.DeleteReason,
	)
	return i, err
}

const updateTenderLetter = `-- name: UpdateTenderLetter :exec
UPDATE tender_letters SET name = $3, kind = $4, template_content = $5, is_default = $6
WHERE id = $1 AND tenant_id = $2
`

type UpdateTenderLetterParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	Name            string    `json:"name"`
	Kind            string    `json:"kind"`
	TemplateContent string    `json:"template_content"`
	IsDefault       bool      `json:"is_default"`
}

func (q *Queries) UpdateTenderLetter(ctx context.Context, arg UpdateTenderLetterParams) error {
	_, err := q.db.Exec(ctx, updateTenderLetter,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Kind,
		arg.TemplateContent,
		arg.IsDefault,
	)
	return err
}
