// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, role_id, email, name, password_hash, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	RoleID       pgtype.UUID `json:"role_id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	PasswordHash string      `json:"password_hash"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.RoleID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1 AND tenant_id = $2
`

type DeleteUserParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.TenantID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserByEmailAnyTenant = `-- name: GetUserByEmailAnyTenant :one
SELECT id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmailAnyTenant(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAnyTenant, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at FROM users WHERE verification_token = $1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserWithRoleByID = `-- name: GetUserWithRoleByID :one
SELECT u.id, u.tenant_id, u.role_id, u.email, u.name, u.password_hash, u.status, u.avatar_url, u.created_at, u.updated_at, u.email_verified_at, u.verification_token, u.verification_expires_at, r.name AS role_name
FROM users u
LEFT JOIN roles r ON r.id = u.role_id
WHERE u.id = $1
`

type GetUserWithRoleByIDRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	RoleID                pgtype.UUID        `json:"role_id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	PasswordHash          string             `json:"password_hash"`
	Status                string             `json:"status"`
	AvatarUrl             *string            `json:"avatar_url"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
	RoleName              *string            `json:"role_name"`
}

func (q *Queries) GetUserWithRoleByID(ctx context.Context, id uuid.UUID) (GetUserWithRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRoleByID, id)
	var i GetUserWithRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
		&i.RoleName,
	)
	return i, err
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT u.id, u.tenant_id, u.role_id, u.email, u.name, u.password_hash, u.status, u.avatar_url, u.created_at, u.updated_at, u.email_verified_at, u.verification_token, u.verification_expires_at, r.name AS role_name
FROM users u
LEFT JOIN roles r ON r.id = u.role_id
WHERE u.tenant_id = $1
ORDER BY u.created_at ASC
`

type ListUsersWithRoleRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              uuid.UUID          `json:"tenant_id"`
	RoleID                pgtype.UUID        `json:"role_id"`
	Email                 string             `json:"email"`
	Name                  string             `json:"name"`
	PasswordHash          string             `json:"password_hash"`
	Status                string             `json:"status"`
	AvatarUrl             *string            `json:"avatar_url"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	EmailVerifiedAt       pgtype.Timestamptz `json:"email_verified_at"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
	RoleName              *string            `json:"role_name"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context, tenantID uuid.UUID) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRoleRow
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Status,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailVerifiedAt,
			&i.VerificationToken,
			&i.VerificationExpiresAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users
SET status = 'active', email_verified_at = now(), verification_token = NULL, verification_expires_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at
`

func (q *Queries) MarkUserVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users SET verification_token = $2, verification_expires_at = $3
WHERE id = $1
`

type SetVerificationTokenParams struct {
	ID                    uuid.UUID          `json:"id"`
	VerificationToken     *string            `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.ID, arg.VerificationToken, arg.VerificationExpiresAt)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at
`

type UpdateUserRoleParams struct {
	ID     uuid.UUID   `json:"id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.RoleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, role_id, email, name, password_hash, status, avatar_url, created_at, updated_at, email_verified_at, verification_token, verification_expires_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerifiedAt,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}
