FROM golang:1.26-alpine AS build
WORKDIR /src
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG BIN=api
RUN CGO_ENABLED=0 go build -o /out/app ./cmd/${BIN}

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build /out/app ./app
EXPOSE 8080
ENTRYPOINT ["./app"]
